/**
 * Brief `sections` values are generated by Gemini with response_mime_type
 * "application/json" and NO response_schema, so the value type is unconstrained.
 * A key that has always been prose can arrive as a nested object.
 *
 * On 2026-08-07 the morning brief shipped
 *   sections.sector_spotlight = { "Consumer & Retail": "<prose>" }
 * where every prior brief had a plain string. The render path called .trim() on
 * it, threw TypeError during render, and the error boundary replaced the whole
 * page with "This page couldn't load".
 *
 * Coerce to a string instead of trusting the type. Never throws.
 */
export function sectionText(value: unknown): string {
  if (typeof value === "string") return value;
  if (value && typeof value === "object" && !Array.isArray(value)) {
    return Object.entries(value as Record<string, unknown>)
      .filter(([, v]) => typeof v === "string" && v.trim())
      .map(([k, v]) => `${k}: ${(v as string).trim()}`)
      .join(" ");
  }
  return "";
}
