import type { CompanyDetail, CompanyDetailArticle } from "./getCompanyDetail";

const NVIDIA_ARTICLES: CompanyDetailArticle[] = [
  {
    id: "fix-nvda-1",
    title: "NVIDIA Posts Q1 Beat as Data-Center Revenue Hits $39.1B",
    source: "Bloomberg",
    url: "https://example.com/nvda-q1-beat",
    publishedAt: "2026-05-04T14:00:00Z",
    sentiment: "bullish",
    dealType: "EARNINGS",
    relevanceScore: 96,
    sector: "Technology",
    summary: "NVIDIA reported Q1 results above consensus, with data-center revenue of $39.1B driven by sustained hyperscaler demand and Hopper-to-Blackwell mix shift.",
    ingestedAt: "2026-05-04T14:30:00Z",
    sourceWinRate: 72,
    sourceSampleSize: 48,
    completeness: "summary",
  },
  {
    id: "fix-nvda-2",
    title: "Microsoft Lifts FY26 Capex to $96B; Cites Demand Above Available Compute",
    source: "Wall Street Journal",
    url: "https://example.com/msft-capex",
    publishedAt: "2026-05-03T17:00:00Z",
    sentiment: "bullish",
    dealType: null,
    relevanceScore: 89,
    sector: "Technology",
    summary: "Microsoft raised FY26 capex guidance to $96B, with management noting demand continues to exceed available compute capacity through year-end.",
    ingestedAt: "2026-05-03T17:15:00Z",
    sourceWinRate: 68,
    sourceSampleSize: 31,
    completeness: "summary",
  },
  {
    id: "fix-nvda-3",
    title: "BIS Considering Tighter H20 Performance Cap on China-Bound SKUs",
    source: "Financial Times",
    url: "https://example.com/bis-h20",
    publishedAt: "2026-05-02T09:30:00Z",
    sentiment: "bearish",
    dealType: "REGULATORY",
    relevanceScore: 88,
    sector: "Technology",
    summary: "BIS is weighing a tighter performance cap on H20 SKUs destined for China, which would further constrain NVIDIA's export licence pathway for the segment.",
    ingestedAt: "2026-05-02T09:45:00Z",
    sourceWinRate: 65,
    sourceSampleSize: 22,
    completeness: "summary",
  },
];

export const NVIDIA_FIXTURE: CompanyDetail = {
  canonical: "NVIDIA",
  display: "NVIDIA",
  ticker: "NVDA",
  exchange: "NASDAQ",
  sector: "Technology",
  industry: null,
  aliases: [
    "Nvidia",
    "NVIDIA",
    "Nvidia Corp.",
    "Nvidia Corp",
    "NVIDIA Corp.",
    "NVIDIA Corporation",
  ],
  aliasMentions: [
    { name: "Nvidia", n: 86 },
    { name: "Nvidia Corp.", n: 12 },
    { name: "NVIDIA", n: 10 },
    { name: "NVIDIA Corporation", n: 3 },
    { name: "Nvidia Corp", n: 1 },
    { name: "NVIDIA Corp.", n: 1 },
  ],
  mentions: 113,
  mentions7d: [8, 14, 11, 0, 12, 6, 10, 0],
  sentiment7d: [0.88, 0.71, 0.91, 0.5, 0.79, 0.67, 0.85, 0.5],
  articles: NVIDIA_ARTICLES,
  themes: ["AI", "Earnings", "Data center", "Geopolitics", "Public Markets"],
  memo: null,
  isPrivate: false,
};
