-- TIS beta member allowlist
-- 57 emails (55 USC + 2 Gmail)

insert into public.beta_allowlist (email, added_by, notes) values
  ('jaquette@usc.edu', 'tis-launch', 'TIS member'),
  ('lmbennet@usc.edu', 'tis-launch', 'TIS member'),
  ('mial@usc.edu', 'tis-launch', 'TIS member'),
  ('dkakar@usc.edu', 'tis-launch', 'TIS member'),
  ('anderson79ryan@gmail.com', 'tis-launch', 'TIS member'),
  ('eovando@usc.edu', 'tis-launch', 'TIS member'),
  ('avyamain@usc.edu', 'tis-launch', 'TIS member'),
  ('vivaanp@usc.edu', 'tis-launch', 'TIS member'),
  ('mwexler@usc.edu', 'tis-launch', 'TIS member'),
  ('cpbowen@usc.edu', 'tis-launch', 'TIS member'),
  ('aarushsh@usc.edu', 'tis-launch', 'TIS member'),
  ('jsodi@usc.edu', 'tis-launch', 'TIS member'),
  ('vbshah@usc.edu', 'tis-launch', 'TIS member'),
  ('sashatan@usc.edu', 'tis-launch', 'TIS member'),
  ('darer@usc.edu', 'tis-launch', 'TIS member'),
  ('matuseno@usc.edu', 'tis-launch', 'TIS member'),
  ('ikoutnou@usc.edu', 'tis-launch', 'TIS member'),
  ('jtwait@usc.edu', 'tis-launch', 'TIS member'),
  ('rbpatel@usc.edu', 'tis-launch', 'TIS member'),
  ('pushengl@usc.edu', 'tis-launch', 'TIS member'),
  ('achen681@usc.edu', 'tis-launch', 'TIS member'),
  ('anggala@usc.edu', 'tis-launch', 'TIS member'),
  ('nzweinbe@usc.edu', 'tis-launch', 'TIS member'),
  ('desaiaa@usc.edu', 'tis-launch', 'TIS member'),
  ('arthurvi@usc.edu', 'tis-launch', 'TIS member'),
  ('junhwang@usc.edu', 'tis-launch', 'TIS member'),
  ('adampokh@usc.edu', 'tis-launch', 'TIS member'),
  ('kluge@usc.edu', 'tis-launch', 'TIS member'),
  ('evankwok@usc.edu', 'tis-launch', 'TIS member'),
  ('brsheffi@usc.edu', 'tis-launch', 'TIS member'),
  ('rithwick@usc.edu', 'tis-launch', 'TIS member'),
  ('menell@usc.edu', 'tis-launch', 'TIS member'),
  ('topalogl@usc.edu', 'tis-launch', 'TIS member'),
  ('stellazh@usc.edu', 'tis-launch', 'TIS member'),
  ('shivansh@usc.edu', 'tis-launch', 'TIS member'),
  ('avmercer@usc.edu', 'tis-launch', 'TIS member'),
  ('cadigan@usc.edu', 'tis-launch', 'TIS member'),
  ('maikins@usc.edu', 'tis-launch', 'TIS member'),
  ('junyuhu@usc.edu', 'tis-launch', 'TIS member'),
  ('rkatraga@usc.edu', 'tis-launch', 'TIS member'),
  ('stongaon@usc.edu', 'tis-launch', 'TIS member'),
  ('harrys@usc.edu', 'tis-launch', 'TIS member'),
  ('brennanj@usc.edu', 'tis-launch', 'TIS member'),
  ('tessahon@usc.edu', 'tis-launch', 'TIS member'),
  ('maxjlee@usc.edu', 'tis-launch', 'TIS member'),
  ('aarushj17@gmail.com', 'tis-launch', 'TIS member'),
  ('joeychen@usc.edu', 'tis-launch', 'TIS member'),
  ('csattira@usc.edu', 'tis-launch', 'TIS member'),
  ('maxpeter@usc.edu', 'tis-launch', 'TIS member'),
  ('melfi@usc.edu', 'tis-launch', 'TIS member'),
  ('masonfel@usc.edu', 'tis-launch', 'TIS member'),
  ('ianting@usc.edu', 'tis-launch', 'TIS member'),
  ('bajoria@usc.edu', 'tis-launch', 'TIS member'),
  ('rsthomps@usc.edu', 'tis-launch', 'TIS member'),
  ('quirch@usc.edu', 'tis-launch', 'TIS member'),
  ('coppe@usc.edu', 'tis-launch', 'TIS member'),
  ('hhaslem@usc.edu', 'tis-launch', 'TIS member')
on conflict (email) do nothing;

-- Verify count (expect ~57 + existing users + Noah)
select count(*) as total_after_tis from public.beta_allowlist;
