-- SEC CIK backfill (REVIEW-ONLY; apply manually after adjudication).
-- Generated by backend/scripts/backfill_sec_ciks.py on 2026-06-04.
-- B1 (clean) + B2 (share-class) only; B3 suspects are EXCLUDED and
-- listed in 2026-06-04-sec-cik-backfill-report.md for adjudication.
-- Idempotent: only touches sec_cik and only where currently NULL.

BEGIN;

-- B1: 185 rows
UPDATE companies SET sec_cik = 825313 WHERE id = '6b5f489d-1ec0-4f34-bd05-f5071d52bf46' AND sec_cik IS NULL;  -- AB 'AllianceBernstein' -> 'ALLIANCEBERNSTEIN HOLDING L.P.' (ratio 0.89)
UPDATE companies SET sec_cik = 1739445 WHERE id = 'c4dad810-7aea-4c3c-a862-82b01b3d5796' AND sec_cik IS NULL;  -- ACA 'ACA' -> 'Arcosa, Inc.' (ratio 0.67)
UPDATE companies SET sec_cik = 1680062 WHERE id = '3b189e72-b133-4cd8-9189-78ce752abf4c' AND sec_cik IS NULL;  -- ACMR 'ACM Research' -> 'ACM Research, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1803696 WHERE id = 'caada12e-87c7-4ed1-a630-cb14f61e390e' AND sec_cik IS NULL;  -- ADEA 'Adeia Inc.' -> 'Adeia Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1803696 WHERE id = 'f50e5c36-0950-45df-ac4f-a9d1d55284de' AND sec_cik IS NULL;  -- ADEA 'Adeia' -> 'Adeia Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1040470 WHERE id = '7cd4a682-1d29-4aca-bab5-8cd42532dcac' AND sec_cik IS NULL;  -- AEHR 'Aehr Test Systems Inc.' -> 'AEHR TEST SYSTEMS' (ratio 1.00)
UPDATE companies SET sec_cik = 1771007 WHERE id = 'a8840278-effb-47e1-886e-3f63e7be0ec1' AND sec_cik IS NULL;  -- AFYA 'Afya Limited' -> 'Afya Ltd' (ratio 1.00)
UPDATE companies SET sec_cik = 880266 WHERE id = 'b417af2d-67cf-4daa-8d20-ca667d796e81' AND sec_cik IS NULL;  -- AGCO 'Agco' -> 'AGCO CORP /DE' (ratio 0.73)
UPDATE companies SET sec_cik = 1577526 WHERE id = '4253d3bc-c51e-4740-bc6a-09b2e5f8f2f3' AND sec_cik IS NULL;  -- AI 'C3.ai' -> 'C3.ai, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 819793 WHERE id = '51bfd180-adc9-4263-b43b-4cad34c602af' AND sec_cik IS NULL;  -- AIN 'Albany International Corp.' -> 'ALBANY INTERNATIONAL CORP /DE/' (ratio 0.80)
UPDATE companies SET sec_cik = 1341235 WHERE id = '4520dc9d-bf3e-41e2-a257-fd5e92711eef' AND sec_cik IS NULL;  -- ALDX 'Aldeyra Therapeutics, Inc.' -> 'Aldeyra Therapeutics, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 897077 WHERE id = 'fa983849-8cd7-4e78-aa0a-7462dae1181c' AND sec_cik IS NULL;  -- ALG 'Alamo Group' -> 'ALAMO GROUP INC' (ratio 1.00)
UPDATE companies SET sec_cik = 766421 WHERE id = '64088d20-13a1-4df6-9fec-01b5e720dcb0' AND sec_cik IS NULL;  -- ALK 'Alaska Air' -> 'ALASKA AIR GROUP, INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 1828805 WHERE id = 'b3c237ca-1163-4b63-96b3-b3556deb94ac' AND sec_cik IS NULL;  -- ALMU 'Luma' -> 'Aeluma, Inc.' (ratio 0.80)
UPDATE companies SET sec_cik = 1034670 WHERE id = '5363a58c-8ed2-4082-91d1-aa5583758a8d' AND sec_cik IS NULL;  -- ALV 'ALV' -> 'AUTOLIV INC' (ratio 0.60)
UPDATE companies SET sec_cik = 1937891 WHERE id = '217f0e17-34ee-469e-9dad-a27ad693bb2a' AND sec_cik IS NULL;  -- AMCI 'AMC Robotics Corporation' -> 'AMC Robotics Corp' (ratio 1.00)
UPDATE companies SET sec_cik = 2031688 WHERE id = '7badaea9-9532-43d5-ad57-b671c21aeca9' AND sec_cik IS NULL;  -- ANPA 'Sparkle' -> 'Rich Sparkle Holdings Ltd' (ratio 0.74)
UPDATE companies SET sec_cik = 2044255 WHERE id = 'ebfea412-35de-4523-8d34-705cc719e8fa' AND sec_cik IS NULL;  -- ANTA 'Antalpha' -> 'Antalpha Platform Holding Co' (ratio 0.64)
UPDATE companies SET sec_cik = 1437402 WHERE id = '01a34460-268f-4547-a0bd-f3143f54b99d' AND sec_cik IS NULL;  -- ARDX 'Ely' -> 'ARDELYX, INC.' (ratio 0.60)
UPDATE companies SET sec_cik = 894871 WHERE id = 'cc28edce-435a-447d-a7b8-5b165f9eeb1d' AND sec_cik IS NULL;  -- AREN 'Arena' -> 'Arena Group Holdings, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1997350 WHERE id = '2eefcee3-a379-40eb-a7a5-dfe2bc680c5a' AND sec_cik IS NULL;  -- ARX 'Accel' -> 'Accelerant Holdings' (ratio 0.67)
UPDATE companies SET sec_cik = 792987 WHERE id = '61a72f12-3c9b-4a01-a2f2-e2e799828f30' AND sec_cik IS NULL;  -- ASTE 'Astec Industries' -> 'ASTEC INDUSTRIES INC' (ratio 1.00)
UPDATE companies SET sec_cik = 1083446 WHERE id = '16c82c40-6d67-477c-b684-72527084c09e' AND sec_cik IS NULL;  -- ASTH 'Astrana Health' -> 'Astrana Health, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1368622 WHERE id = '55da5c2b-a1cc-45c2-921d-4dc14399f9cb' AND sec_cik IS NULL;  -- AVAV 'AeroVironment' -> 'AeroVironment Inc' (ratio 1.00)
UPDATE companies SET sec_cik = 1368622 WHERE id = 'cf04beca-f993-44ee-a5a1-31b96496c3d0' AND sec_cik IS NULL;  -- AVAV 'AeroVironment, Inc.' -> 'AeroVironment Inc' (ratio 1.00)
UPDATE companies SET sec_cik = 2096300 WHERE id = 'e7fa975d-f088-4f59-a674-53137f1410a6' AND sec_cik IS NULL;  -- AVEX 'Aevex' -> 'AEVEX Corp.' (ratio 1.00)
UPDATE companies SET sec_cik = 1606498 WHERE id = '226af746-d45e-4afc-bb9e-2970757d000a' AND sec_cik IS NULL;  -- AVNS 'Avanos Medical' -> 'AVANOS MEDICAL, INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 1051627 WHERE id = '79087126-c9a5-444f-8aa2-626677d8f9e9' AND sec_cik IS NULL;  -- AXTI 'AXTI' -> 'AXT INC' (ratio 0.86)
UPDATE companies SET sec_cik = 1051627 WHERE id = 'd57dd8c3-52fc-44f0-b574-457e91a6316f' AND sec_cik IS NULL;  -- AXTI 'AXT Inc' -> 'AXT INC' (ratio 1.00)
UPDATE companies SET sec_cik = 1443646 WHERE id = '38feb1ad-7bf8-476c-83cd-0399a08f5acc' AND sec_cik IS NULL;  -- BAH 'Booz Allen Hamilton' -> 'Booz Allen Hamilton Holding Corp' (ratio 1.00)
UPDATE companies SET sec_cik = 1703956 WHERE id = 'd686dd03-db2a-4f38-93ad-986798bc07a7' AND sec_cik IS NULL;  -- BBCP 'Concrete Pumping Holdings' -> 'Concrete Pumping Holdings, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1655050 WHERE id = '709b96e8-0c8c-4bc7-8229-549577dd5ab9' AND sec_cik IS NULL;  -- BCSF 'Bain Capital Insurance' -> 'Bain Capital Specialty Finance, Inc.' (ratio 0.73)
UPDATE companies SET sec_cik = 2070849 WHERE id = 'afdb214f-842e-4992-87de-d229503097c6' AND sec_cik IS NULL;  -- BLLN 'BillionToOne' -> 'BillionToOne, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1830043 WHERE id = '536c53a4-f318-421a-9efb-ea3d95124507' AND sec_cik IS NULL;  -- BMBL 'Bumble' -> 'Bumble Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1815021 WHERE id = 'd85d0933-5d27-457c-964f-4e105b96b755' AND sec_cik IS NULL;  -- BQ 'Boqii Holding Limited' -> 'Boqii Holding Ltd' (ratio 1.00)
UPDATE companies SET sec_cik = 1619762 WHERE id = 'e4a55ee7-aa8a-4401-89d6-918097c0d589' AND sec_cik IS NULL;  -- BRSL 'Brightstar' -> 'Brightstar Lottery PLC' (ratio 0.71)
UPDATE companies SET sec_cik = 1130144 WHERE id = '6f172ab0-e3ca-4ab8-98c0-f664e53df711' AND sec_cik IS NULL;  -- BSRR 'Sierra' -> 'SIERRA BANCORP' (ratio 0.60)
UPDATE companies SET sec_cik = 1436229 WHERE id = 'fb08b1a6-192a-4386-a052-e92ce0fcc526' AND sec_cik IS NULL;  -- BTCS 'TCS' -> 'BTCS Inc.' (ratio 0.86)
UPDATE companies SET sec_cik = 1725123 WHERE id = 'bf5e02f2-616a-4f26-878e-e5a4077ba1d6' AND sec_cik IS NULL;  -- CANG 'Cango Inc.' -> 'Cango Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 944148 WHERE id = 'b410bf1d-07d3-4e23-b61f-1b52b7b21d80' AND sec_cik IS NULL;  -- CBZ 'CBIZ' -> 'CBIZ, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1582982 WHERE id = '2df1dbb7-2fdf-4ed6-b9ef-3865ab7f18e4' AND sec_cik IS NULL;  -- CCLD 'CareCloud' -> 'CareCloud, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1486159 WHERE id = 'bf01fba2-886e-445e-a64d-a18c42477670' AND sec_cik IS NULL;  -- CHRD 'Chord Energy' -> 'Chord Energy Corp' (ratio 1.00)
UPDATE companies SET sec_cik = 1766502 WHERE id = '4394e74d-5c08-46ff-bb74-852006423093' AND sec_cik IS NULL;  -- CHWY 'Chewy' -> 'Chewy, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 796505 WHERE id = '1b7ce253-71a4-4539-a183-5c2532f50644' AND sec_cik IS NULL;  -- CLFD 'Learfield' -> 'Clearfield, Inc.' (ratio 0.95)
UPDATE companies SET sec_cik = 1764046 WHERE id = '0ebf64c3-8ac9-4f43-8499-5388fe651c6f' AND sec_cik IS NULL;  -- CLVT 'Clarivate Plc' -> 'CLARIVATE PLC' (ratio 1.00)
UPDATE companies SET sec_cik = 1764046 WHERE id = '4ca395a7-0617-4d66-83ea-e5871bfc4161' AND sec_cik IS NULL;  -- CLVT 'Clarivate' -> 'CLARIVATE PLC' (ratio 1.00)
UPDATE companies SET sec_cik = 1050377 WHERE id = '650a3e47-fbde-4d50-b7a8-7f9d7ef3896f' AND sec_cik IS NULL;  -- CNXN 'PC Connection Inc' -> 'PC CONNECTION INC' (ratio 1.00)
UPDATE companies SET sec_cik = 1024305 WHERE id = 'e9761678-ee8a-4fc1-9c24-b4d848b59584' AND sec_cik IS NULL;  -- COTY 'Coty Inc.' -> 'COTY INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 1375877 WHERE id = '9a5f6ed4-d5bf-46f1-894a-1983c1090f08' AND sec_cik IS NULL;  -- CSIQ 'Canadian Solar Inc.' -> 'Canadian Solar Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1375877 WHERE id = 'adb3df4e-282d-4006-bf54-3b6bb96373a7' AND sec_cik IS NULL;  -- CSIQ 'Canadian Solar' -> 'Canadian Solar Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1169561 WHERE id = '1e7daf46-e23e-4282-a25c-09cc091c99c6' AND sec_cik IS NULL;  -- CVLT 'Commvault' -> 'COMMVAULT SYSTEMS INC' (ratio 0.69)
UPDATE companies SET sec_cik = 1169561 WHERE id = 'f77b0041-09ad-41c2-80a5-4a7aa72b4aed' AND sec_cik IS NULL;  -- CVLT 'Commvault Systems' -> 'COMMVAULT SYSTEMS INC' (ratio 1.00)
UPDATE companies SET sec_cik = 1866368 WHERE id = '8a20f20e-9dbf-437a-baf5-ca684905aa3e' AND sec_cik IS NULL;  -- CWAN 'Clearwater' -> 'Clearwater Analytics Holdings, Inc.' (ratio 0.67)
UPDATE companies SET sec_cik = 810958 WHERE id = '4de7c02f-aef1-4998-aa67-4f346c68955d' AND sec_cik IS NULL;  -- CZNC 'Citizens & Northern' -> 'CITIZENS & NORTHERN CORP' (ratio 1.00)
UPDATE companies SET sec_cik = 1308547 WHERE id = '4115fb1d-2fa5-4584-91a3-2df75d93ba60' AND sec_cik IS NULL;  -- DLB 'Dolby Laboratories' -> 'Dolby Laboratories, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 868780 WHERE id = '515d06ce-a138-4ea9-8562-4e749b5335a6' AND sec_cik IS NULL;  -- DORM 'Dorman Products' -> 'Dorman Products, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1853825 WHERE id = 'd0b8de74-c35f-4667-8aab-cb0750bc63f2' AND sec_cik IS NULL;  -- DTCX 'Datacentrex, Inc.' -> 'Datacentrex, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1819928 WHERE id = '7655fce6-2326-4d0c-9a53-23de51d2d41b' AND sec_cik IS NULL;  -- DV 'DoubleVerify' -> 'DoubleVerify Holdings, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1463101 WHERE id = '88397940-d8d9-4f38-a65d-08c77c5bf8be' AND sec_cik IS NULL;  -- ENPH 'Enphase Energy, Inc.' -> 'Enphase Energy, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1632790 WHERE id = '4a642544-ff96-4cae-9f28-3b699a0557d2' AND sec_cik IS NULL;  -- ENR 'Energizer Holdings, Inc.' -> 'ENERGIZER HOLDINGS, INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 1805077 WHERE id = '9d66d94f-8b5b-4fcf-ac4e-f6fa75c48731' AND sec_cik IS NULL;  -- EOSE 'Eos Energy Enterprises, Inc.' -> 'Eos Energy Enterprises, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 887396 WHERE id = 'f70b1c49-4c4d-4ec9-b75c-757334a24743' AND sec_cik IS NULL;  -- EP 'Empire Petroleum' -> 'EMPIRE PETROLEUM CORP' (ratio 1.00)
UPDATE companies SET sec_cik = 859070 WHERE id = '65a8b0fd-279f-466d-9dc3-5991ea098b26' AND sec_cik IS NULL;  -- FCBC 'Community Bankshares, Inc.' -> 'FIRST COMMUNITY BANKSHARES INC /VA/' (ratio 0.82)
UPDATE companies SET sec_cik = 1056288 WHERE id = 'c4225bb4-d022-4859-b10a-008650781f4a' AND sec_cik IS NULL;  -- FHI 'Federated Hermes' -> 'FEDERATED HERMES, INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 1288847 WHERE id = '46716629-ad42-4be7-97a4-5d132352ae5d' AND sec_cik IS NULL;  -- FIVN 'Five9 Inc' -> 'Five9, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1288847 WHERE id = '910d58e9-2013-4539-b700-5bbd388aee6c' AND sec_cik IS NULL;  -- FIVN 'Five9' -> 'Five9, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1947016 WHERE id = '6ffed7d4-4656-4fd8-a878-b8ce62218f73' AND sec_cik IS NULL;  -- FJET 'Starfighters Space, Inc.' -> 'Starfighters Space, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1124198 WHERE id = 'a974f8f2-db21-4fde-8983-f710693f7143' AND sec_cik IS NULL;  -- FLR 'Fluor Corporation' -> 'FLUOR CORP' (ratio 1.00)
UPDATE companies SET sec_cik = 1858724 WHERE id = '9b2da8df-abcb-4158-b47d-7c115045f59a' AND sec_cik IS NULL;  -- FLX 'BingEx Limited' -> 'BingEx Ltd' (ratio 1.00)
UPDATE companies SET sec_cik = 2024656 WHERE id = '25d28d67-839e-4c92-b3cd-520abb6ffc11' AND sec_cik IS NULL;  -- FMFC 'Kandal M Venture Limited' -> 'Kandal M Venture Ltd' (ratio 1.00)
UPDATE companies SET sec_cik = 1023313 WHERE id = 'c19eb98d-fc05-4763-89c0-0cdc94511fdf' AND sec_cik IS NULL;  -- FORR 'Forrester Research' -> 'FORRESTER RESEARCH, INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 2071778 WHERE id = '7fa64d8e-842f-4a13-b461-38a121184973' AND sec_cik IS NULL;  -- FRMI 'Fermi' -> 'Fermi Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1800667 WHERE id = 'c5105c16-5ac7-4faf-8d9d-7fc0f1f3e11f' AND sec_cik IS NULL;  -- FROG 'JFrog' -> 'JFrog Ltd' (ratio 1.00)
UPDATE companies SET sec_cik = 1517413 WHERE id = '49244cd2-f257-47f7-a351-25a4b8b98271' AND sec_cik IS NULL;  -- FSLY 'Fastly' -> 'Fastly, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1517413 WHERE id = 'df1a1edc-3851-4d82-917b-974640ed0b24' AND sec_cik IS NULL;  -- FSLY 'Fastly Inc.' -> 'Fastly, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1819796 WHERE id = '9c2a3d3e-abf9-4984-9cf7-c9bbcb8994ac' AND sec_cik IS NULL;  -- GCMG 'GCM Grosvenor' -> 'GCM Grosvenor Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 2055592 WHERE id = '17f390fb-b13a-4087-88b1-0552ef9bb6de' AND sec_cik IS NULL;  -- GEMI 'Gemini Space Station, Inc.' -> 'Gemini Space Station, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1557860 WHERE id = '0f248fc5-eeb0-4a90-94ab-297eb923c438' AND sec_cik IS NULL;  -- GLOB 'Globant' -> 'Globant S.A.' (ratio 0.78)
UPDATE companies SET sec_cik = 1820144 WHERE id = '5e6c2320-9f41-479d-a054-cb5961936803' AND sec_cik IS NULL;  -- GRND 'Grindr Inc.' -> 'Grindr Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1572616 WHERE id = '2007ef6c-0fce-4fff-a50d-4df6086639b5' AND sec_cik IS NULL;  -- GUTS 'Fractyl Health, Inc.' -> 'FRACTYL HEALTH, INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 1773751 WHERE id = 'bcbe250f-06ab-4189-9b18-72ec8d071c5b' AND sec_cik IS NULL;  -- HIMS 'Hims & Hers Health' -> 'Hims & Hers Health, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1822492 WHERE id = '1e898b8e-34b1-48cd-90fa-ce79d960e529' AND sec_cik IS NULL;  -- HLMN 'Hillman Solutions Corp.' -> 'Hillman Solutions Corp.' (ratio 1.00)
UPDATE companies SET sec_cik = 1433642 WHERE id = 'c50b5874-f892-4698-8ab2-74fdb460e1d5' AND sec_cik IS NULL;  -- HLNE 'Hamilton Lane' -> 'Hamilton Lane INC' (ratio 1.00)
UPDATE companies SET sec_cik = 1331520 WHERE id = '838a40d8-43f2-4b41-b117-b994bab3cb69' AND sec_cik IS NULL;  -- HOMB 'Home BancShares, Inc.' -> 'HOME BANCSHARES INC' (ratio 1.00)
UPDATE companies SET sec_cik = 1428336 WHERE id = '66ac0c80-4ae4-4777-bea5-ca714d75826e' AND sec_cik IS NULL;  -- HQY 'HealthEquity' -> 'HEALTHEQUITY, INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 2023153 WHERE id = '5e98ab79-3b32-4220-8160-81b130baad41' AND sec_cik IS NULL;  -- HTLM 'HomesToLife' -> 'HomesToLife Ltd' (ratio 1.00)
UPDATE companies SET sec_cik = 766829 WHERE id = 'dec1887e-a62e-4554-bab5-26973acf07e6' AND sec_cik IS NULL;  -- HTO 'H2O America' -> 'H2O AMERICA' (ratio 1.00)
UPDATE companies SET sec_cik = 940942 WHERE id = 'd1b14966-f6c9-4ca4-a8c3-269d264c4bbd' AND sec_cik IS NULL;  -- HUBG 'Hub Group, Inc.' -> 'Hub Group, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1682639 WHERE id = 'dbfc56c1-584c-497b-aa80-13d9feaf44e4' AND sec_cik IS NULL;  -- HYPD 'Hyperion' -> 'HYPERION DEFI, INC.' (ratio 0.76)
UPDATE companies SET sec_cik = 1203464 WHERE id = 'f86d5d42-135e-49d8-8f49-5184ad39fe17' AND sec_cik IS NULL;  -- IAG 'IAG' -> 'IAMGOLD CORP' (ratio 0.60)
UPDATE companies SET sec_cik = 1326110 WHERE id = '355d5bc3-5c91-415b-892c-2cf036a8e5f8' AND sec_cik IS NULL;  -- IBRX 'ImmunityBio, Inc.' -> 'ImmunityBio, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 941221 WHERE id = '79765665-7556-4feb-97e8-39cdaf131da3' AND sec_cik IS NULL;  -- ICL 'ICL' -> 'ICL Group Ltd.' (ratio 1.00)
UPDATE companies SET sec_cik = 1057877 WHERE id = '3d27853c-478c-4654-ba6f-c80c926acfae' AND sec_cik IS NULL;  -- IDA 'IDACORP' -> 'IDACORP INC' (ratio 1.00)
UPDATE companies SET sec_cik = 1030192 WHERE id = 'ce5dbc18-46b9-481c-a327-b9f24f74d0a8' AND sec_cik IS NULL;  -- IDR 'Idaho Strategic' -> 'Idaho Strategic Resources, Inc.' (ratio 0.75)
UPDATE companies SET sec_cik = 1676725 WHERE id = '5b885a00-f21c-44be-96bb-7f5e39e3c8ae' AND sec_cik IS NULL;  -- IDYA 'IDEAYA Biosciences, Inc.' -> 'IDEAYA Biosciences, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 903651 WHERE id = 'c85ff9d0-8486-4977-a523-fd6b761bf240' AND sec_cik IS NULL;  -- INOD 'Innodata' -> 'INNODATA INC' (ratio 1.00)
UPDATE companies SET sec_cik = 1722608 WHERE id = '31b261f6-c625-4d06-82c5-51608f59ae35' AND sec_cik IS NULL;  -- IQ 'iQiyi Inc.' -> 'iQIYI, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1325618 WHERE id = '6f29c58b-78d2-4e76-87f0-39d85bc00e5a' AND sec_cik IS NULL;  -- IRMD 'Iradimed' -> 'IRADIMED CORP' (ratio 1.00)
UPDATE companies SET sec_cik = 780571 WHERE id = '8b8432f3-c377-4586-ad06-401b21dcc6de' AND sec_cik IS NULL;  -- ITRI 'Itron' -> 'ITRON, INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 1158463 WHERE id = '054a767b-8988-41b4-9659-f2fc9cf09cf8' AND sec_cik IS NULL;  -- JBLU 'JetBlue' -> 'JETBLUE AIRWAYS CORP' (ratio 0.64)
UPDATE companies SET sec_cik = 1976908 WHERE id = '23a973a8-6266-49db-b15a-0e07b69b38dc' AND sec_cik IS NULL;  -- JDZG 'JIADE LIMITED' -> 'JIADE Ltd' (ratio 1.00)
UPDATE companies SET sec_cik = 1481513 WHERE id = '6179750c-d23e-401d-8596-20f13b886cff' AND sec_cik IS NULL;  -- JKS 'JinkoSolar' -> 'JinkoSolar Holding Co., Ltd.' (ratio 1.00)
UPDATE companies SET sec_cik = 795266 WHERE id = '68caa8d9-751e-42d2-99b9-5ab9a5835cac' AND sec_cik IS NULL;  -- KBH 'KB Home' -> 'KB HOME' (ratio 1.00)
UPDATE companies SET sec_cik = 1311370 WHERE id = '89d83ff6-baec-4948-8c95-1de9f8362c15' AND sec_cik IS NULL;  -- LAZ 'Lazard' -> 'Lazard, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1811210 WHERE id = '3ff40f65-a571-4893-ac20-e2071c94cc06' AND sec_cik IS NULL;  -- LCID 'Lucid Group' -> 'Lucid Group, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1811210 WHERE id = 'ee98f57a-8baa-4b77-8936-829cbcbe2c3b' AND sec_cik IS NULL;  -- LCID 'Lucid' -> 'Lucid Group, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 2052959 WHERE id = '06aef3bc-7bdb-477d-9dbf-aa9e0fe397b8' AND sec_cik IS NULL;  -- LION 'Lionsgate Studios Corp.' -> 'Lionsgate Studios Corp.' (ratio 1.00)
UPDATE companies SET sec_cik = 2052959 WHERE id = 'e8d8f260-7e3d-446b-bd19-8ad4c4f7905a' AND sec_cik IS NULL;  -- LION 'Lionsgate' -> 'Lionsgate Studios Corp.' (ratio 0.69)
UPDATE companies SET sec_cik = 1844452 WHERE id = 'd9da0e4c-f5c7-4a21-8628-9fbc2fcd0c73' AND sec_cik IS NULL;  -- LUNR 'Intuitive Machines' -> 'Intuitive Machines, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1325964 WHERE id = '6c083149-0fc9-4313-9057-1c558b1c4e26' AND sec_cik IS NULL;  -- LWLG 'Lightwave Logic Inc' -> 'Lightwave Logic, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1759509 WHERE id = '2f9ebdaf-68d8-4b8f-9725-938b7b47caf4' AND sec_cik IS NULL;  -- LYFT 'Lyft Inc.' -> 'Lyft, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1759509 WHERE id = 'c7ebfb5b-7c4b-4525-8096-1554fda72495' AND sec_cik IS NULL;  -- LYFT 'Lyft' -> 'Lyft, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 912242 WHERE id = '32750385-e801-4c93-88df-e98916dd7508' AND sec_cik IS NULL;  -- MAC 'Acer' -> 'MACERICH CO' (ratio 0.67)
UPDATE companies SET sec_cik = 1520358 WHERE id = '8b8d2f49-316e-464e-84a1-efab92bba070' AND sec_cik IS NULL;  -- MAMA "Mama's Creations" -> "Mama's Creations, Inc." (ratio 1.00)
UPDATE companies SET sec_cik = 1596967 WHERE id = '063301f7-350f-4f9b-8c14-c1715c361ca3' AND sec_cik IS NULL;  -- MC 'Moelis & Company' -> 'Moelis & Co' (ratio 1.00)
UPDATE companies SET sec_cik = 1853513 WHERE id = 'c553f593-b914-41df-a224-46e9d9e5b5ad' AND sec_cik IS NULL;  -- MCW 'Mister Car Wash, Inc.' -> 'Mister Car Wash, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1333274 WHERE id = 'fbae723c-e5e2-4d0e-9b22-d58245fb241a' AND sec_cik IS NULL;  -- MERC 'Mercer' -> 'MERCER INTERNATIONAL INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 789570 WHERE id = '6920c772-3ab2-437b-a2fe-aa8f26b116ef' AND sec_cik IS NULL;  -- MGM 'MGM Resorts' -> 'MGM Resorts International' (ratio 1.00)
UPDATE companies SET sec_cik = 1595974 WHERE id = '737231a9-aa51-4df3-932b-5e39d3482bc8' AND sec_cik IS NULL;  -- MGNI 'Magnite' -> 'MAGNITE, INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 1902314 WHERE id = '6267fc00-fd1b-479b-b838-916b6d73da8a' AND sec_cik IS NULL;  -- MPTI 'M-tron Industries, Inc.' -> 'M-tron Industries, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1522767 WHERE id = '51a41933-423a-4f21-89d2-0a1148629fe4' AND sec_cik IS NULL;  -- MRMD 'MariMed' -> 'MARIMED INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 891103 WHERE id = '8c9f2189-7854-47cb-aaf8-64ea7d153ee9' AND sec_cik IS NULL;  -- MTCH 'Match Group' -> 'Match Group, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1513761 WHERE id = '82675c6d-9c0c-4744-a7ce-eb5d0547b7d9' AND sec_cik IS NULL;  -- NCLH 'Norwegian Cruise Line Holdings' -> 'Norwegian Cruise Line Holdings Ltd.' (ratio 1.00)
UPDATE companies SET sec_cik = 1513761 WHERE id = 'b325a350-201a-4d2e-aa67-c4ba76c0bfb1' AND sec_cik IS NULL;  -- NCLH 'Norwegian Cruise Line' -> 'Norwegian Cruise Line Holdings Ltd.' (ratio 1.00)
UPDATE companies SET sec_cik = 1513761 WHERE id = 'cad3d3a4-d732-46d2-a837-77c1eb08234b' AND sec_cik IS NULL;  -- NCLH 'Norwegian Cruise' -> 'Norwegian Cruise Line Holdings Ltd.' (ratio 0.86)
UPDATE companies SET sec_cik = 1744781 WHERE id = '6033b2ca-8801-4974-8947-6f38e3f7e4a3' AND sec_cik IS NULL;  -- NIU 'Niu Technologies' -> 'Niu Technologies' (ratio 1.00)
UPDATE companies SET sec_cik = 2063196 WHERE id = 'c1f3ce75-e89d-431f-9fdd-7f9613779661' AND sec_cik IS NULL;  -- NTSK 'Netskope' -> 'Netskope Inc' (ratio 1.00)
UPDATE companies SET sec_cik = 1142417 WHERE id = '616276e9-e324-4d82-85c3-6bf64789451f' AND sec_cik IS NULL;  -- NXST 'Nexstar' -> 'NEXSTAR MEDIA GROUP, INC.' (ratio 0.70)
UPDATE companies SET sec_cik = 1004702 WHERE id = '536d56e8-6ef5-4ac7-a6c1-29ea9791adba' AND sec_cik IS NULL;  -- OCFC 'OceanFirst Financial Corp.' -> 'OCEANFIRST FINANCIAL CORP' (ratio 1.00)
UPDATE companies SET sec_cik = 1821825 WHERE id = 'a18bcdb8-623c-4b27-9530-23a2f0a66d0f' AND sec_cik IS NULL;  -- OGN 'Organon' -> 'Organon & Co.' (ratio 1.00)
UPDATE companies SET sec_cik = 812074 WHERE id = 'c6e58d11-6d41-4655-ad2c-5c4e0eea6f5f' AND sec_cik IS NULL;  -- OI 'O-I Glass' -> 'O-I Glass, Inc. /DE/' (ratio 0.86)
UPDATE companies SET sec_cik = 1868726 WHERE id = 'c4b6ca23-aac1-4271-94f1-61ceba1f1865' AND sec_cik IS NULL;  -- OLPX 'Olaplex' -> 'OLAPLEX HOLDINGS, INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 791963 WHERE id = 'e7722d38-a7f7-4f9e-b80b-e5c4903bbdd4' AND sec_cik IS NULL;  -- OPY 'Oppenheimer' -> 'OPPENHEIMER HOLDINGS INC' (ratio 1.00)
UPDATE companies SET sec_cik = 1796280 WHERE id = 'c7b57c3a-045b-42ac-8201-55fecf50d754' AND sec_cik IS NULL;  -- ORIC 'ORIC Pharmaceuticals, Inc.' -> 'Oric Pharmaceuticals, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1402829 WHERE id = 'b4e9f402-26c9-403f-8b2d-795fd69f2a36' AND sec_cik IS NULL;  -- ORN 'Orion' -> 'Orion Group Holdings Inc' (ratio 1.00)
UPDATE companies SET sec_cik = 1466593 WHERE id = '9d1cd60e-bef2-4d39-9edf-b1da89c98ce4' AND sec_cik IS NULL;  -- OTTR 'Otter' -> 'Otter Tail Corp' (ratio 0.67)
UPDATE companies SET sec_cik = 1835597 WHERE id = 'cb143018-9d4e-44c1-b053-913ab5602e64' AND sec_cik IS NULL;  -- PEPG 'PepGen Inc.' -> 'PepGen Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 931015 WHERE id = '0ad1d03a-8b4b-469d-85a2-3c1a309ab8f5' AND sec_cik IS NULL;  -- PII 'Polaris' -> 'Polaris Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1230245 WHERE id = 'dacb8029-1c4a-4cc5-8c4a-71fe3a1395de' AND sec_cik IS NULL;  -- PIPR 'Piper Sandler' -> 'PIPER SANDLER COMPANIES' (ratio 1.00)
UPDATE companies SET sec_cik = 1637207 WHERE id = 'cf685aa2-a809-425a-9afa-420513b97f93' AND sec_cik IS NULL;  -- PLNT 'Planet Fitness' -> 'Planet Fitness, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1383414 WHERE id = 'ea6f6481-dc77-48c6-83a2-a60a954570ce' AND sec_cik IS NULL;  -- PNNT 'ARK Invest' -> 'PENNANTPARK INVESTMENT CORP' (ratio 0.62)
UPDATE companies SET sec_cik = 1437424 WHERE id = '71eaf56d-b6da-4385-bc26-563ed9fe6460' AND sec_cik IS NULL;  -- POET 'Poet Technologies' -> 'POET TECHNOLOGIES INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 1639825 WHERE id = '8d2eb13e-c9fb-4c7e-b770-4526d293d5c3' AND sec_cik IS NULL;  -- PTON 'Peloton Interactive Inc.' -> 'PELOTON INTERACTIVE, INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 1907982 WHERE id = '79013271-f8b0-4938-962f-eb7faf16d7ec' AND sec_cik IS NULL;  -- QBTS 'D-Wave Quantum Inc.' -> 'D-Wave Quantum Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1410384 WHERE id = 'bb286dc6-7822-480e-b12b-3630754b127f' AND sec_cik IS NULL;  -- QTWO 'Q2 Holdings' -> 'Q2 Holdings, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1819810 WHERE id = 'd3e31083-5af0-473e-86b0-ac183323a65c' AND sec_cik IS NULL;  -- RDW 'Redwire' -> 'Redwire Corp' (ratio 1.00)
UPDATE companies SET sec_cik = 1468327 WHERE id = 'b12120fe-24ca-460a-9a7f-0fbbb7f8d6b0' AND sec_cik IS NULL;  -- RENT 'Rent the Runway, Inc.' -> 'Rent the Runway, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1528849 WHERE id = 'd7ac9af1-efe9-4e01-83ab-85ef43968ee8' AND sec_cik IS NULL;  -- RH 'RH' -> 'RH' (ratio 1.00)
UPDATE companies SET sec_cik = 1451505 WHERE id = '56e89443-0d15-4bd2-ace0-b91d3a3a669b' AND sec_cik IS NULL;  -- RIG 'Transocean' -> 'Transocean Ltd.' (ratio 1.00)
UPDATE companies SET sec_cik = 1469367 WHERE id = '7db001e7-c66c-4e4f-839f-040a589f4162' AND sec_cik IS NULL;  -- RUN 'Sunrun' -> 'Sunrun Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1329394 WHERE id = '292bfba1-fb98-45cb-a469-26a1f5124016' AND sec_cik IS NULL;  -- SIMO 'Silicon Motion' -> 'Silicon Motion Technology CORP' (ratio 0.72)
UPDATE companies SET sec_cik = 908937 WHERE id = 'f2c4a105-1fcd-4605-a19a-00b1d8add3dc' AND sec_cik IS NULL;  -- SIRI 'Sirius XM' -> 'SIRIUS XM HOLDINGS INC.' (ratio 1.00)
UPDATE companies SET sec_cik = 1794942 WHERE id = '146461b3-bdce-4c24-a1fa-678eb0fea06c' AND sec_cik IS NULL;  -- SKFG 'Stark' -> 'Stark Focus Group, Inc.' (ratio 0.62)
UPDATE companies SET sec_cik = 893538 WHERE id = '893cc798-9bfb-4159-977e-7b2414c44fa2' AND sec_cik IS NULL;  -- SM 'SM Energy' -> 'SM Energy Co' (ratio 1.00)
UPDATE companies SET sec_cik = 1564408 WHERE id = '1aa61989-11c9-49f5-9735-b5f64c3d85d3' AND sec_cik IS NULL;  -- SNAP 'Snap, Inc.' -> 'Snap Inc' (ratio 1.00)
UPDATE companies SET sec_cik = 1564408 WHERE id = '3f486192-3ced-4bb0-ba30-cc655eb04d4f' AND sec_cik IS NULL;  -- SNAP 'Snap' -> 'Snap Inc' (ratio 1.00)
UPDATE companies SET sec_cik = 1564408 WHERE id = 'bf2f62fb-e01c-42a7-9805-807747988f2c' AND sec_cik IS NULL;  -- SNAP 'Snap Inc.' -> 'Snap Inc' (ratio 1.00)
UPDATE companies SET sec_cik = 1417663 WHERE id = '0714c74c-91d7-4f3f-a2f3-a61ede356387' AND sec_cik IS NULL;  -- SNWV 'Sanuwave' -> 'SANUWAVE Health, Inc.' (ratio 0.70)
UPDATE companies SET sec_cik = 1314727 WHERE id = '0de32cfd-d913-4126-9dff-25ae4681555b' AND sec_cik IS NULL;  -- SONO 'Sonos Inc.' -> 'Sonos Inc' (ratio 1.00)
UPDATE companies SET sec_cik = 876883 WHERE id = 'f737dfad-dc19-4c3b-b053-9af81124a3fb' AND sec_cik IS NULL;  -- STGW 'Stagwell' -> 'Stagwell Inc' (ratio 1.00)
UPDATE companies SET sec_cik = 1227636 WHERE id = '260039b9-794d-422f-8f4d-b91b8b74f5e0' AND sec_cik IS NULL;  -- STIM 'Neuronetics' -> 'Neuronetics, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1337634 WHERE id = 'c518f3bc-fac5-47f7-be39-f0b03e0fdbbb' AND sec_cik IS NULL;  -- STUB 'StubHub' -> 'StubHub Holdings, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 2092574 WHERE id = '7ae30ee7-81b4-4d2c-8c59-aa4d4ad86aa2' AND sec_cik IS NULL;  -- SWMR 'Swarmer Inc.' -> 'Swarmer, Inc' (ratio 1.00)
UPDATE companies SET sec_cik = 2092574 WHERE id = '93342bbc-3bbc-439e-9d60-343aed01b43a' AND sec_cik IS NULL;  -- SWMR 'Swarmer' -> 'Swarmer, Inc' (ratio 1.00)
UPDATE companies SET sec_cik = 817720 WHERE id = '1b770275-3084-4f18-8925-cd4e0369f6e2' AND sec_cik IS NULL;  -- SYNA 'Synaptics' -> 'SYNAPTICS Inc' (ratio 1.00)
UPDATE companies SET sec_cik = 1169445 WHERE id = '6864d94f-b981-4b2c-adf1-08a40f0b366e' AND sec_cik IS NULL;  -- TBRG 'TruBridge' -> 'TruBridge, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1712189 WHERE id = '45bdd9a2-affd-46a4-96c0-e7f30f691f15' AND sec_cik IS NULL;  -- TH 'Target Hospitality Corp.' -> 'Target Hospitality Corp.' (ratio 1.00)
UPDATE companies SET sec_cik = 1130598 WHERE id = '0e27274b-e96d-43e9-8a8d-edbac7fee4a1' AND sec_cik IS NULL;  -- TRAW 'Traws Pharma' -> 'Traws Pharma, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1845840 WHERE id = '92add784-6469-4aae-8789-8e0e4f9c6870' AND sec_cik IS NULL;  -- TSAT 'Telesat' -> 'Telesat Corp' (ratio 1.00)
UPDATE companies SET sec_cik = 1970622 WHERE id = '93431c5d-9b26-400b-a602-bc2ba5206534' AND sec_cik IS NULL;  -- USAR 'USA Rare Earth Inc.' -> 'USA Rare Earth, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1970622 WHERE id = 'dbbe4b16-0313-46d5-97da-6af7b4ffba06' AND sec_cik IS NULL;  -- USAR 'USA Rare Earth' -> 'USA Rare Earth, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1524358 WHERE id = 'b409c0d2-5107-42dd-94b7-27a56b7426aa' AND sec_cik IS NULL;  -- VAC 'Marriott Vacations' -> 'MARRIOTT VACATIONS WORLDWIDE Corp' (ratio 0.78)
UPDATE companies SET sec_cik = 1570827 WHERE id = '24be262f-3bca-4bc7-a986-e7abffb37b54' AND sec_cik IS NULL;  -- VCTR 'Victory Capital' -> 'Victory Capital Holdings, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1468091 WHERE id = '5d7e0aaf-ce75-4b99-bedc-a75e696437f9' AND sec_cik IS NULL;  -- VEON 'Veon Ltd.' -> 'VEON Ltd.' (ratio 1.00)
UPDATE companies SET sec_cik = 2067876 WHERE id = 'f031d3cc-8e17-4a79-a645-badad16c8001' AND sec_cik IS NULL;  -- VSNT 'Versant' -> 'Versant Media Group, Inc.' (ratio 0.70)
UPDATE companies SET sec_cik = 1636222 WHERE id = '5af58b51-fd21-424d-aacd-bbce170fb9c7' AND sec_cik IS NULL;  -- WING 'Wingstop' -> 'Wingstop Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1288403 WHERE id = 'd0000bc9-d35a-448b-ad31-9417ed96851e' AND sec_cik IS NULL;  -- WTI 'W&T Offshore, Inc.' -> 'W&T OFFSHORE INC' (ratio 1.00)
UPDATE companies SET sec_cik = 1034760 WHERE id = '4c1737a2-289f-448b-88e0-470e30775300' AND sec_cik IS NULL;  -- WYY 'WidePoint Corporation' -> 'WIDEPOINT CORP' (ratio 1.00)
UPDATE companies SET sec_cik = 2088896 WHERE id = '5dd6a1f4-2134-47be-add5-aed494d99b07' AND sec_cik IS NULL;  -- XE 'X-Energy' -> 'X-Energy, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 2088896 WHERE id = 'f9f0ddbb-aeef-480b-b6e8-63b5d4adc8e8' AND sec_cik IS NULL;  -- XE 'X-energy' -> 'X-Energy, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1657573 WHERE id = '2feb8a57-380a-4b7f-b8cf-3f736ea14c39' AND sec_cik IS NULL;  -- XMTR 'METR' -> 'Xometry, Inc.' (ratio 0.73)
UPDATE companies SET sec_cik = 1345016 WHERE id = 'b07fda7b-3b55-4e54-a372-26b622190245' AND sec_cik IS NULL;  -- YELP 'Yelp' -> 'YELP INC' (ratio 1.00)
UPDATE companies SET sec_cik = 1614178 WHERE id = '93b221b6-1687-4a3c-8a37-a8c56dc5d0ef' AND sec_cik IS NULL;  -- YEXT 'Yext' -> 'Yext, Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 2028177 WHERE id = '06e9ff7c-8f55-4325-90cd-4f06d8596882' AND sec_cik IS NULL;  -- YOUL 'Youlife Group Inc.' -> 'Youlife Group Inc.' (ratio 1.00)
UPDATE companies SET sec_cik = 1985337 WHERE id = '92a1aeed-24e4-42b1-a8e7-0a32e9df3dae' AND sec_cik IS NULL;  -- YYGH 'YY Group' -> 'YY Group Holding Ltd.' (ratio 1.00)

-- B2: 38 rows
UPDATE companies SET sec_cik = 1824502 WHERE id = '8e22758b-24a8-491e-9763-34a645b1e658' AND sec_cik IS NULL;  -- ACHR 'Archer Aviation' -> 'Archer Aviation Inc.' (ratio 1.00) classes=ACHR,ACHR-WT
UPDATE companies SET sec_cik = 1004434 WHERE id = '02210ffd-0a8d-492e-92bb-179c43622fa8' AND sec_cik IS NULL;  -- AMG 'Affiliated Managers' -> 'AFFILIATED MANAGERS GROUP, INC.' (ratio 1.00) classes=AMG,MGR,MGRB,MGRD,MGRE
UPDATE companies SET sec_cik = 1860805 WHERE id = '438dc798-9197-4c0d-ac92-5e102a24b50c' AND sec_cik IS NULL;  -- ASTL 'Algoma Steel Group Inc.' -> 'Algoma Steel Group Inc.' (ratio 1.00) classes=ASTL,ASTLW
UPDATE companies SET sec_cik = 1130713 WHERE id = 'e76815a3-0afc-4eff-8483-a37aeef7a6d1' AND sec_cik IS NULL;  -- BBBY 'Bed Bath & Beyond' -> 'BED BATH & BEYOND, INC.' (ratio 1.00) classes=BBBY,BBBY-WT
UPDATE companies SET sec_cik = 1067983 WHERE id = 'de144271-920b-443f-a26b-3f9f30097c0a' AND sec_cik IS NULL;  -- BRK.B 'Berkshire Hathaway' -> 'BERKSHIRE HATHAWAY INC' (ratio 1.00) classes=BRK-A,BRK-B
UPDATE companies SET sec_cik = 1679688 WHERE id = '6a6d1b44-8652-4401-b814-c73b72298570' AND sec_cik IS NULL;  -- DBRG 'DigitalBridge' -> 'DigitalBridge Group, Inc.' (ratio 1.00) classes=DBRG,DBRG-PH,DBRG-PI,DBRG-PJ
UPDATE companies SET sec_cik = 1849635 WHERE id = 'ec0f53dd-5481-491d-8a9e-bc62b8216394' AND sec_cik IS NULL;  -- DJT 'Trump Media' -> 'Trump Media & Technology Group Corp.' (ratio 0.67) classes=DJT,DJTWW
UPDATE companies SET sec_cik = 1867102 WHERE id = '8ea30178-0ecb-4872-8c91-23d2ccff7489' AND sec_cik IS NULL;  -- EVTL 'Vertical Aerospace Ltd.' -> 'Vertical Aerospace Ltd.' (ratio 1.00) classes=EVAWF,EVBWF,EVTL,EVTWF
UPDATE companies SET sec_cik = 886128 WHERE id = 'a8ab6585-7197-424c-92f5-74494e332616' AND sec_cik IS NULL;  -- FCEL 'FuelCell Energy Inc' -> 'FUELCELL ENERGY INC' (ratio 1.00) classes=FCEL,FCELB
UPDATE companies SET sec_cik = 1818382 WHERE id = '63ace41f-7e14-43b5-9c4c-81026117b939' AND sec_cik IS NULL;  -- HUMA 'Humacyte, Inc.' -> 'Humacyte, Inc.' (ratio 1.00) classes=HUMA,HUMAW
UPDATE companies SET sec_cik = 1400891 WHERE id = '908a0c8b-2fc3-4b05-a683-2ae5addbb7b5' AND sec_cik IS NULL;  -- IHRT 'iHeartMedia' -> 'iHeartMedia, Inc.' (ratio 1.00) classes=IHETW,IHRT,IHRTB
UPDATE companies SET sec_cik = 1072627 WHERE id = 'd06a465a-9353-4046-b45b-264744265703' AND sec_cik IS NULL;  -- KFS 'Kingsway Financial' -> 'KINGSWAY Corp' (ratio 0.62) classes=KFS,KWY
UPDATE companies SET sec_cik = 1849820 WHERE id = '270e6bab-f6df-4c60-ba04-6119d73d8c33' AND sec_cik IS NULL;  -- KITT 'Nauticus Robotics, Inc.' -> 'Nauticus Robotics, Inc.' (ratio 1.00) classes=KITT,KITTW
UPDATE companies SET sec_cik = 2062440 WHERE id = '03377873-ef0b-4ace-8793-976c90d9a2b9' AND sec_cik IS NULL;  -- KYIV 'Kyivstar' -> 'Kyivstar Group Ltd.' (ratio 1.00) classes=KYIV,KYIVW
UPDATE companies SET sec_cik = 2062440 WHERE id = '2239177f-a489-4d72-9f3b-6b8a84aa1550' AND sec_cik IS NULL;  -- KYIV 'Kyivstar Group Ltd.' -> 'Kyivstar Group Ltd.' (ratio 1.00) classes=KYIV,KYIVW
UPDATE companies SET sec_cik = 2077033 WHERE id = 'c232f69e-678f-4fe6-b7f1-bbb06786bf22' AND sec_cik IS NULL;  -- MMTX 'Miluna Acquisition Corp.' -> 'Miluna Acquisition Corp' (ratio 1.00) classes=MMTX,MMTXU,MMTXW
UPDATE companies SET sec_cik = 1898643 WHERE id = '3b5be110-fba0-4f46-8405-d49dba31bad2' AND sec_cik IS NULL;  -- MOB 'Mobilicom' -> 'Mobilicom Ltd' (ratio 1.00) classes=MOB,MOBBW
UPDATE companies SET sec_cik = 1496099 WHERE id = '4d8cac62-77d3-4f1a-a17e-93695dd7f1d5' AND sec_cik IS NULL;  -- NMFC 'New Mountain Capital' -> 'New Mountain Finance Corp' (ratio 0.70) classes=NMFC,NMFCZ
UPDATE companies SET sec_cik = 1496099 WHERE id = '5589e523-cc99-43d9-a3e6-b6ffd8b55cc1' AND sec_cik IS NULL;  -- NMFC 'New Mountain' -> 'New Mountain Finance Corp' (ratio 0.75) classes=NMFC,NMFCZ
UPDATE companies SET sec_cik = 1076930 WHERE id = '433ce5f7-faf1-47c2-b55a-10dcb0125de1' AND sec_cik IS NULL;  -- NOVT 'Vanta' -> 'NOVANTA INC' (ratio 0.83) classes=NOVT,NOVTU
UPDATE companies SET sec_cik = 1969302 WHERE id = '1e912c24-c0d2-46d6-a675-cf5a86890c2f' AND sec_cik IS NULL;  -- PONY 'Pony AI' -> 'Pony AI Inc.' (ratio 1.00) classes=PONY,PYAIF
UPDATE companies SET sec_cik = 1969302 WHERE id = '6105d8f5-1a43-468f-8437-5f8462600241' AND sec_cik IS NULL;  -- PONY 'Pony AI Inc.' -> 'Pony AI Inc.' (ratio 1.00) classes=PONY,PYAIF
UPDATE companies SET sec_cik = 1840856 WHERE id = '0a6457ac-2371-4296-9ad8-1f6d37b3c66f' AND sec_cik IS NULL;  -- SOUN 'SoundHound AI Inc' -> 'SOUNDHOUND AI, INC.' (ratio 1.00) classes=SOUN,SOUNW
UPDATE companies SET sec_cik = 1840856 WHERE id = '73a44307-be79-406e-b27b-61f88a6a81c5' AND sec_cik IS NULL;  -- SOUN 'SoundHound' -> 'SOUNDHOUND AI, INC.' (ratio 0.87) classes=SOUN,SOUNW
UPDATE companies SET sec_cik = 1840856 WHERE id = 'b6a3a272-fcbc-4017-8beb-6d29799a591c' AND sec_cik IS NULL;  -- SOUN 'SoundHound AI' -> 'SOUNDHOUND AI, INC.' (ratio 1.00) classes=SOUN,SOUNW
UPDATE companies SET sec_cik = 1210708 WHERE id = 'af7b693a-2286-439c-9021-0907537660ab' AND sec_cik IS NULL;  -- STRR 'Star Equity Holdings' -> 'Star Equity Holdings, Inc.' (ratio 1.00) classes=STRR,STRRP
UPDATE companies SET sec_cik = 1875609 WHERE id = 'afcf0df0-abeb-4517-b581-df8e61495d97' AND sec_cik IS NULL;  -- SWVL 'Swvl' -> 'Swvl Holdings Corp' (ratio 1.00) classes=SWVL,SWVLW
UPDATE companies SET sec_cik = 1798562 WHERE id = 'f66e0049-1615-49ec-b0e8-6b6566a95523' AND sec_cik IS NULL;  -- TMC 'The Metals Company' -> 'TMC the metals Co Inc.' (ratio 0.75) classes=TMC,TMCWW
UPDATE companies SET sec_cik = 1046179 WHERE id = '4da26598-77cf-4afa-be6c-6028c7f436a9' AND sec_cik IS NULL;  -- TSM 'Taiwan Semiconductor Manufacturing Company' -> 'TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD' (ratio 1.00) classes=TSM,TSMWF
UPDATE companies SET sec_cik = 1046179 WHERE id = '4f407d59-87b6-4c3c-84e6-84c2a477457f' AND sec_cik IS NULL;  -- TSM 'Taiwan Semiconductor Manufacturing Company Limited (TSM)' -> 'TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD' (ratio 0.94) classes=TSM,TSMWF
UPDATE companies SET sec_cik = 1046179 WHERE id = '77700ef7-e51a-4ab0-81dd-e276345cc0e2' AND sec_cik IS NULL;  -- TSM 'Taiwan Semiconductor' -> 'TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD' (ratio 0.74) classes=TSM,TSMWF
UPDATE companies SET sec_cik = 1046179 WHERE id = '9f39e37f-043a-4a3d-9fa8-375ecd611c60' AND sec_cik IS NULL;  -- TSM 'Taiwan Semiconductor Manufacturing Company Limited' -> 'TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD' (ratio 1.00) classes=TSM,TSMWF
UPDATE companies SET sec_cik = 1046179 WHERE id = 'bddaa156-9cd1-4816-90ae-ddc242e5bf7e' AND sec_cik IS NULL;  -- TSM 'Taiwan Semiconductor Manufacturing' -> 'TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD' (ratio 1.00) classes=TSM,TSMWF
UPDATE companies SET sec_cik = 1046179 WHERE id = 'e126bcb4-6ff7-4eef-b5ac-4a784b975fdb' AND sec_cik IS NULL;  -- TSM 'Taiwan Semiconductor Manufacturing Co.' -> 'TAIWAN SEMICONDUCTOR MANUFACTURING CO LTD' (ratio 1.00) classes=TSM,TSMWF
UPDATE companies SET sec_cik = 1336917 WHERE id = 'ff4809c7-fb8c-442a-a643-7accb91a0b69' AND sec_cik IS NULL;  -- UAA 'Under Armour' -> 'Under Armour, Inc.' (ratio 1.00) classes=UA,UAA
UPDATE companies SET sec_cik = 1913510 WHERE id = '7fabaa05-f465-4f8e-873a-406a5e676a69' AND sec_cik IS NULL;  -- VFS 'VinFast' -> 'VinFast Auto Ltd.' (ratio 0.74) classes=VFS,VFSWW
UPDATE companies SET sec_cik = 806968 WHERE id = '018ac423-92a1-42b8-bfcd-9b3bda25c392' AND sec_cik IS NULL;  -- WPP 'WPP' -> 'WPP plc' (ratio 1.00) classes=WPP,WPPGF
UPDATE companies SET sec_cik = 1819493 WHERE id = '2ec51764-0963-4b3e-a4e6-9f701913f068' AND sec_cik IS NULL;  -- XOS 'Xos' -> 'Xos, Inc.' (ratio 1.00) classes=XOS,XOSWW

-- B3-A: significant-token sets equal after stripping legal suffixes, high-confidence same entity
-- 1 rows; keep or cut this block wholesale
UPDATE companies SET sec_cik = 1809104 WHERE id = 'abd17073-5969-4b40-ba1d-292ffcfbef9c' AND sec_cik IS NULL;  -- ALIT 'Alight, Inc.' -> 'Alight, Inc. / Delaware' (tokens: alight)

COMMIT;
