"use client";

import type { ReactNode } from "react";
import { BackHeader, SectionRule } from "@/components/mobile/screen-chrome";
import { TabBarClearance } from "@/components/mobile/tab-bar-clearance";
import { FONT_DISPLAY, FONT_MONO, FONT_SANS } from "@/components/mobile/fonts";
import styles from "@/components/mobile/mobile.module.css";
import { neutralizeThesisTitle, verdictDisplayLabel } from "@/lib/track-record-live-score";
import { componentBreakdown, SCORE_SCALE } from "@/lib/score-presentation";
import { OUTCOME_TOKENS } from "@/components/ledger";
import {
  instrumentLine,
  leanTokens,
  longDateTime,
  type TrackerThesis,
} from "./tracker-model";
import { reviewVerdictLabel } from "./tracker-screen";

/**
 * One thesis and the evidence behind it, on a phone.
 *
 * THE BACK CONTROL NAMES THE TRACKER, so it is a plain link and not
 * `historyAware`: the rule in `screen-chrome.tsx` is that a control promising
 * a destination goes on promising it. The reader can reach this screen from
 * the tracker, and only from the tracker, so the two agree today; the label is
 * what keeps them agreeing if a second entry point ever appears.
 *
 * WHAT THE PROTOTYPE DRAWS THAT IS NOT HERE, and why. All four are reported in
 * the PR rather than quietly dropped.
 *
 *   CALL-0413        an invented call number. `theses` has a uuid.
 *   "what you wrote" the prototype frames the rationale as the reader's own
 *                    prose. A thesis is generated by the desk; there is no
 *                    user-authored field on the row, and putting the reader's
 *                    name on the desk's reasoning is the sharpest untruth
 *                    available on this screen.
 *   "SETTLES <date>" `check_after` is when the grader next looks, not when the
 *                    thesis settles. The grader settles on accumulated
 *                    evidence and the shipped copy says so in as many words.
 *   "A direction,
 *    never a score"  the shipped screen renders the composite and every
 *                    component value that sums into it. It is one thesis's
 *                    reading on a stated scale, not an aggregate and not a
 *                    rate, so it is kept.
 */

const PAD = "var(--v3-pad)";
const BACK_HREF = "/radar/track-record";
const BACK_LABEL = "Evidence tracker";

export type ThesisStage = "loading" | "error" | "missing" | "ready";

export interface ThesisScreenData {
  thesis: TrackerThesis | null;
  rationale: string | null;
  catalyst: string | null;
  bearCase: string | null;
  /** Latest verdict fields, for the plain-language component sentences. */
  priceChangePct: number | null;
  conviction: string | null;
  latestConfidence: number | null;
  rawSentimentAlignment: number | null;
  rawSupportingRatio: number | null;
}

export function ThesisScreen({ stage, data }: { stage: ThesisStage; data: ThesisScreenData }) {
  const t = data.thesis;

  return (
    <div
      data-parity="thesis"
      className={styles.enter}
      style={{
        backgroundColor: "var(--c-bg)",
        minHeight: "calc(100dvh - var(--mobile-tabbar-height) - env(safe-area-inset-bottom))",
        padding: 0,
      }}
    >
      <BackHeader href={BACK_HREF} label={BACK_LABEL} />

      <div style={{ padding: `20px ${PAD} 24px` }}>
        {stage === "loading" ? <ThesisSkeleton /> : null}
        {stage === "error" ? <ThesisError /> : null}
        {stage === "missing" ? <ThesisMissing /> : null}
        {stage === "ready" && t ? <ThesisBody t={t} data={data} /> : null}
      </div>

      <TabBarClearance />
    </div>
  );
}

/* ── the thesis itself ──────────────────────────────────────────────── */

function ThesisBody({ t, data }: { t: TrackerThesis; data: ThesisScreenData }) {
  const lean = leanTokens(t.live.verdict, t.reviews.length > 0);
  const eyebrow = instrumentLine(t);
  const settled = t.live.terminal === "confirmed" || t.live.terminal === "invalidated";

  const readings = componentBreakdown(t.live.components, {
    priceChangePct: data.priceChangePct,
    ticker: t.ticker,
    conviction: data.conviction,
    ageDays: t.live.ageDays,
    horizonDays: t.live.horizonDays,
    latestConfidence: data.latestConfidence,
    latestVerdict: t.live.terminal,
    rawSentimentAlignment: data.rawSentimentAlignment,
    rawSupportingRatio: data.rawSupportingRatio,
  });

  return (
    <>
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          gap: "10px",
        }}
      >
        <span
          style={{
            minWidth: 0,
            font: `500 10px/1.3 ${FONT_MONO}`,
            letterSpacing: "0.07em",
            color: "var(--c-muted)",
            overflowWrap: "anywhere",
          }}
        >
          {eyebrow ?? "NO INSTRUMENT NAMED"}
        </span>
        <span style={{ flex: "none", font: `600 11px/1.3 ${FONT_SANS}`, color: lean.text }}>
          {lean.word}
        </span>
      </div>

      <h1
        style={{
          margin: "14px 0 0",
          font: `600 21px/1.32 ${FONT_DISPLAY}`,
          letterSpacing: "-0.01em",
          color: "var(--c-ink)",
          textWrap: "pretty",
        }}
      >
        {neutralizeThesisTitle(t.title)}
      </h1>

      <p
        style={{
          margin: "13px 0 0",
          font: `400 10px/1.7 ${FONT_MONO}`,
          letterSpacing: "0.07em",
          color: "var(--c-muted)",
          textWrap: "pretty",
        }}
      >
        {metaLine(t)}
      </p>

      {/* ── current reading ── */}
      <SectionRule label="what we’re seeing" marginTop="22px" />
      <div style={{ marginTop: "11px", display: "flex", alignItems: "center", gap: "10px" }}>
        <span
          style={{
            flex: "none",
            display: "inline-block",
            width: "7px",
            height: "7px",
            borderRadius: "50%",
            backgroundColor: lean.dot,
          }}
          aria-hidden="true"
        />
        <span style={{ font: `600 13px/1 ${FONT_SANS}`, color: lean.text }}>{lean.word}</span>
        <span style={{ font: `400 12px/1 ${FONT_MONO}`, color: "var(--c-secondary)" }}>
          {t.live.score > 0 ? "+" : ""}
          {t.live.score} of &plusmn;{SCORE_SCALE}
        </span>
      </div>

      <div style={{ marginTop: "12px", display: "flex", flexDirection: "column" }}>
        {readings.map((r, i) => (
          <div
            key={r.label}
            style={{
              display: "flex",
              gap: "11px",
              alignItems: "flex-start",
              padding: "11px 0",
              borderTop: "1px solid var(--c-hair)",
              borderBottom: i === readings.length - 1 ? "1px solid var(--c-hair)" : undefined,
            }}
          >
            <span
              aria-hidden="true"
              style={{
                flex: "none",
                marginTop: "5px",
                display: "inline-block",
                width: "7px",
                height: "7px",
                borderRadius: "50%",
                backgroundColor:
                  r.sentiment === "positive"
                    ? OUTCOME_TOKENS.supported.dot
                    : r.sentiment === "negative"
                      ? OUTCOME_TOKENS.challenged.dot
                      : "var(--c-edge)",
              }}
            />
            <div style={{ minWidth: 0, flex: 1 }}>
              <div style={{ font: `600 12.5px/1.4 ${FONT_SANS}`, color: "var(--c-ink)" }}>
                {r.label}
              </div>
              <div
                style={{
                  marginTop: "3px",
                  font: `400 12px/1.5 ${FONT_SANS}`,
                  color: "var(--c-body)",
                  textWrap: "pretty",
                }}
              >
                {r.sentence}{" "}
                <span style={{ font: `400 10px/1.5 ${FONT_MONO}`, color: "var(--c-muted)" }}>
                  ({r.value > 0 ? "+" : ""}
                  {Math.round(r.value)})
                </span>
              </div>
            </div>
          </div>
        ))}
      </div>

      <p
        style={{
          margin: "12px 0 0",
          font: `400 11px/1.55 ${FONT_SANS}`,
          color: "var(--c-muted)",
          textWrap: "pretty",
        }}
      >
        Those are the five readings behind the composite. The composite itself is the figure the
        nightly run persisted, so it need not be the exact sum of the five rounded readings above
        it. A terminal verdict, Supported or Challenged, is the grader&rsquo;s judgement of the
        accumulated evidence and is not triggered by the composite crossing a fixed line. Age{" "}
        {t.live.ageDays}d against a {t.live.horizonDays}d horizon.
      </p>

      {/* ── the desk's own reasoning ── */}
      {data.rationale ? (
        <Prose label="rationale">{data.rationale}</Prose>
      ) : null}
      {data.catalyst ? <Prose label="catalyst">{data.catalyst}</Prose> : null}
      {data.bearCase ? <Prose label="bear case">{data.bearCase}</Prose> : null}

      {/* ── review timeline ── */}
      <div style={{ marginTop: "22px", display: "flex", alignItems: "center", gap: "11px" }}>
        <span style={{ font: `400 italic 12.5px/1 ${FONT_DISPLAY}`, color: "var(--c-secondary)" }}>
          review timeline
        </span>
        <span aria-hidden="true" style={{ flex: 1, height: "1px", backgroundColor: "var(--c-border)" }} />
        <span style={{ font: `400 10.5px/1 ${FONT_MONO}`, color: "var(--c-muted)" }}>
          {t.reviews.length}
        </span>
      </div>

      {t.reviews.length === 0 ? (
        <p
          style={{
            margin: "10px 0 0",
            font: `400 12.5px/1.55 ${FONT_SANS}`,
            color: "var(--c-muted)",
            textWrap: "pretty",
          }}
        >
          No review has run against this thesis yet. The nightly pass writes the first one.
        </p>
      ) : (
        <div style={{ marginTop: "12px", display: "flex", flexDirection: "column" }}>
          {/* Newest first. A record read on a phone is read from the top. */}
          {[...t.reviews].reverse().map((r) => {
            const rl = leanTokens(reviewVerdictLabel(r.verdict));
            return (
              <div
                key={r.id}
                style={{
                  padding: "12px 0",
                  borderTop: "1px solid var(--c-hair)",
                  display: "flex",
                  gap: "11px",
                  alignItems: "flex-start",
                }}
              >
                <span
                  aria-hidden="true"
                  style={{
                    flex: "none",
                    marginTop: "4px",
                    display: "inline-block",
                    width: "9px",
                    height: "9px",
                    borderRadius: "50%",
                    backgroundColor: rl.dot,
                  }}
                />
                <div style={{ minWidth: 0, flex: 1 }}>
                  <div
                    style={{
                      display: "flex",
                      alignItems: "baseline",
                      gap: "8px",
                      flexWrap: "wrap",
                    }}
                  >
                    <span style={{ font: `600 11.5px/1.3 ${FONT_SANS}`, color: rl.text }}>
                      {verdictDisplayLabel(reviewVerdictLabel(r.verdict))}
                    </span>
                    <span
                      style={{
                        font: `400 10px/1.3 ${FONT_MONO}`,
                        letterSpacing: "0.05em",
                        color: "var(--c-muted)",
                      }}
                    >
                      {longDateTime(r.gradedAt)}
                    </span>
                  </div>
                  {r.notes ? (
                    <p
                      style={{
                        margin: "7px 0 0",
                        font: `400 12.5px/1.55 ${FONT_SANS}`,
                        color: "var(--c-body)",
                        textWrap: "pretty",
                      }}
                    >
                      {r.notes}
                    </p>
                  ) : null}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* ── what happens next ── */}
      <div
        style={{
          marginTop: "22px",
          padding: "14px 15px",
          border: "1px solid var(--c-border)",
          borderRadius: "12px",
          backgroundColor: "var(--c-surface)",
        }}
      >
        <div
          style={{
            font: `400 10px/1 ${FONT_MONO}`,
            letterSpacing: "0.07em",
            color: "var(--c-muted)",
          }}
        >
          WHAT HAPPENS NEXT
        </div>
        <p
          style={{
            margin: "9px 0 0",
            font: `400 13px/1.6 ${FONT_SANS}`,
            color: "var(--c-body)",
            textWrap: "pretty",
          }}
        >
          {settled
            ? "This thesis has reached a terminal verdict. It stays on the record, and nothing further is graded against it."
            : `Reviewed again tonight at 8:10 PM PT on the global daily run. The grader settles a thesis as Supported or Challenged once it has accumulated sufficient evidence, which usually takes several reviews with consistent price action behind them. ${horizonSentence(t)}`}
        </p>
      </div>
    </>
  );
}

/* ── pieces ─────────────────────────────────────────────────────────── */

function Prose({ label, children }: { label: string; children: ReactNode }) {
  return (
    <>
      <SectionRule label={label} marginTop="22px" />
      <p
        style={{
          margin: "11px 0 0",
          font: `400 13px/1.62 ${FONT_SANS}`,
          color: "var(--c-body)",
          textWrap: "pretty",
        }}
      >
        {children}
      </p>
    </>
  );
}

/**
 * The head's mono line. Every part is a real column, and a part with no value
 * is omitted rather than filled: "REVIEWED NIGHTLY" is the one constant, and
 * it states the cron rather than a date this row does not carry.
 */
function metaLine(t: TrackerThesis): string {
  const parts: string[] = [];
  if (t.generatedAt) parts.push(`GENERATED ${longDateTime(t.generatedAt).toUpperCase()}`);
  parts.push("REVIEWED NIGHTLY");
  if (t.checkAfter) {
    parts.push(
      `CHECK AFTER ${new Date(t.checkAfter)
        .toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })
        .toUpperCase()}`,
    );
  }
  return parts.join("  ·  ");
}

function horizonSentence(t: TrackerThesis): string {
  const left = t.live.horizonDays - t.live.ageDays;
  if (left < 0) return `It is ${-left} days past its ${t.live.horizonDays}d horizon.`;
  if (left === 0) return `It is at its ${t.live.horizonDays}d horizon today.`;
  return `${left} ${left === 1 ? "day" : "days"} remain on its ${t.live.horizonDays}d horizon.`;
}

/* ── states ─────────────────────────────────────────────────────────── */

function ThesisSkeleton() {
  return (
    <div aria-hidden="true" style={{ display: "flex", flexDirection: "column", gap: "12px" }}>
      <div className={styles.sk} style={{ height: "14px", width: "45%", borderRadius: "4px" }} />
      <div className={styles.sk} style={{ height: "78px", borderRadius: "9px" }} />
      <div className={styles.sk} style={{ height: "160px", borderRadius: "12px" }} />
      <div className={styles.sk} style={{ height: "160px", borderRadius: "12px" }} />
    </div>
  );
}

/**
 * A FAILED READ IS NOT A MISSING ROW. `missing` below says the query answered
 * and this id is not in the table; this one says the query did not answer at
 * all. Collapsing the two tells a reader their thesis was deleted when the
 * network dropped.
 */
function ThesisError() {
  return (
    <div style={panel}>
      <p style={{ margin: 0, font: `500 15px/1.35 ${FONT_DISPLAY}`, color: "var(--c-ink)" }}>
        Could not load this thesis.
      </p>
      <p
        style={{
          margin: "8px 0 0",
          font: `400 12.5px/1.55 ${FONT_SANS}`,
          color: "var(--c-secondary)",
          textWrap: "pretty",
        }}
      >
        The read failed. The thesis and its reviews are unchanged.
      </p>
    </div>
  );
}

function ThesisMissing() {
  return (
    <div style={panel}>
      <p style={{ margin: 0, font: `500 15px/1.35 ${FONT_DISPLAY}`, color: "var(--c-ink)" }}>
        No thesis at this address.
      </p>
      <p
        style={{
          margin: "8px 0 0",
          font: `400 12.5px/1.55 ${FONT_SANS}`,
          color: "var(--c-secondary)",
          textWrap: "pretty",
        }}
      >
        The read answered and nothing came back for this id.
      </p>
    </div>
  );
}

const panel = {
  border: "1px solid var(--c-border)",
  borderRadius: "12px",
  backgroundColor: "var(--c-well)",
  padding: "16px 15px",
} as const;
