-- Backfill display_name for existing watchlist ticker entries that predate
-- the display_name column. Run once in Supabase SQL Editor.
--
-- This uses a static mapping of known tickers to their human-readable names.
-- New entries added via the UI will automatically get display_name from the
-- autocomplete component.

UPDATE watchlist
SET display_name = CASE identifier
  WHEN 'AAPL'    THEN 'Apple Inc'
  WHEN 'MSFT'    THEN 'Microsoft Corporation'
  WHEN 'NVDA'    THEN 'Nvidia Corporation'
  WHEN 'NVDL'    THEN 'GraniteShares 2x Long NVDA Daily ETF'
  WHEN 'GOOGL'   THEN 'Alphabet Inc Class A'
  WHEN 'GOOG'    THEN 'Alphabet Inc Class C'
  WHEN 'META'    THEN 'Meta Platforms Inc'
  WHEN 'AMZN'    THEN 'Amazon.com Inc'
  WHEN 'TSLA'    THEN 'Tesla Inc'
  WHEN 'AMD'     THEN 'Advanced Micro Devices Inc'
  WHEN 'INTC'    THEN 'Intel Corporation'
  WHEN 'AVGO'    THEN 'Broadcom Inc'
  WHEN 'QCOM'    THEN 'Qualcomm Inc'
  WHEN 'ORCL'    THEN 'Oracle Corporation'
  WHEN 'CRM'     THEN 'Salesforce Inc'
  WHEN 'PLTR'    THEN 'Palantir Technologies Inc'
  WHEN 'UBER'    THEN 'Uber Technologies Inc'
  WHEN 'IONQ'    THEN 'IonQ Inc'
  WHEN 'TSM'     THEN 'Taiwan Semiconductor Manufacturing'
  WHEN 'BABA'    THEN 'Alibaba Group Holding'
  WHEN 'NFLX'    THEN 'Netflix Inc'
  WHEN 'DIS'     THEN 'Walt Disney Company'
  WHEN 'PYPL'    THEN 'PayPal Holdings Inc'
  WHEN 'COIN'    THEN 'Coinbase Global Inc'
  WHEN 'JPM'     THEN 'JPMorgan Chase & Co'
  WHEN 'BAC'     THEN 'Bank of America Corporation'
  WHEN 'WFC'     THEN 'Wells Fargo & Company'
  WHEN 'C'       THEN 'Citigroup Inc'
  WHEN 'GS'      THEN 'Goldman Sachs Group Inc'
  WHEN 'MS'      THEN 'Morgan Stanley'
  WHEN 'BLK'     THEN 'BlackRock Inc'
  WHEN 'V'       THEN 'Visa Inc'
  WHEN 'MA'      THEN 'Mastercard Inc'
  WHEN 'BX'      THEN 'Blackstone Inc'
  WHEN 'APO'     THEN 'Apollo Global Management Inc'
  WHEN 'KKR'     THEN 'KKR & Co Inc'
  WHEN 'CG'      THEN 'Carlyle Group Inc'
  WHEN 'BAM'     THEN 'Brookfield Asset Management'
  WHEN 'BRK.B'   THEN 'Berkshire Hathaway Inc Class B'
  WHEN 'BRK'     THEN 'Berkshire Hathaway Inc Class B'
  WHEN 'FCX'     THEN 'Freeport-McMoRan Inc'
  WHEN 'SPMO'    THEN 'Invesco S&P 500 Momentum ETF'
  WHEN 'XOM'     THEN 'Exxon Mobil Corporation'
  WHEN 'CVX'     THEN 'Chevron Corporation'
  WHEN 'JNJ'     THEN 'Johnson & Johnson'
  WHEN 'UNH'     THEN 'UnitedHealth Group Inc'
  WHEN 'LLY'     THEN 'Eli Lilly and Company'
  WHEN 'MRK'     THEN 'Merck & Co Inc'
  WHEN 'ABBV'    THEN 'AbbVie Inc'
  WHEN 'PFE'     THEN 'Pfizer Inc'
  WHEN 'MRNA'    THEN 'Moderna Inc'
  WHEN 'WMT'     THEN 'Walmart Inc'
  WHEN 'COST'    THEN 'Costco Wholesale Corporation'
  WHEN 'TGT'     THEN 'Target Corporation'
  WHEN 'HD'      THEN 'Home Depot Inc'
  WHEN 'SBUX'    THEN 'Starbucks Corporation'
  WHEN 'MCD'     THEN 'McDonald''s Corporation'
  WHEN 'NKE'     THEN 'Nike Inc'
  WHEN 'KO'      THEN 'Coca-Cola Company'
  WHEN 'PEP'     THEN 'PepsiCo Inc'
  WHEN 'BA'      THEN 'Boeing Company'
  WHEN 'LMT'     THEN 'Lockheed Martin Corporation'
  WHEN 'RTX'     THEN 'RTX Corporation'
  WHEN 'NOC'     THEN 'Northrop Grumman Corporation'
  WHEN 'GD'      THEN 'General Dynamics Corporation'
  WHEN 'GE'      THEN 'GE Aerospace'
  WHEN 'CAT'     THEN 'Caterpillar Inc'
  WHEN 'DE'      THEN 'Deere & Company'
  WHEN 'AMT'     THEN 'American Tower Corporation'
  WHEN 'PLD'     THEN 'Prologis Inc'
  WHEN 'EQIX'    THEN 'Equinix Inc'
  WHEN 'NEE'     THEN 'NextEra Energy Inc'
  WHEN 'SPY'     THEN 'SPDR S&P 500 ETF Trust'
  WHEN 'QQQ'     THEN 'Invesco QQQ Trust'
  ELSE display_name  -- keep existing value if already set
END
WHERE type = 'ticker'
  AND (display_name IS NULL OR display_name = '');
