-- Backfill display_name for existing watchlist ticker entries that predate
-- the display_name column (or were added without it).
-- Run once in Supabase SQL Editor.
-- New entries added via the UI autocomplete always include display_name.

-- Using a single UPDATE with CASE for efficiency:
UPDATE watchlist
SET display_name = CASE identifier
  -- Technology
  WHEN 'AAPL'   THEN 'Apple Inc'
  WHEN 'MSFT'   THEN 'Microsoft Corporation'
  WHEN 'NVDA'   THEN 'Nvidia Corporation'
  WHEN 'NVDL'   THEN 'GraniteShares 2x Long NVDA Daily ETF'
  WHEN 'GOOGL'  THEN 'Alphabet Inc Class A'
  WHEN 'GOOG'   THEN 'Alphabet Inc Class C'
  WHEN 'META'   THEN 'Meta Platforms Inc'
  WHEN 'AMZN'   THEN 'Amazon.com Inc'
  WHEN 'TSLA'   THEN 'Tesla Inc'
  WHEN 'AMD'    THEN 'Advanced Micro Devices Inc'
  WHEN 'INTC'   THEN 'Intel Corporation'
  WHEN 'AVGO'   THEN 'Broadcom Inc'
  WHEN 'QCOM'   THEN 'Qualcomm Inc'
  WHEN 'TXN'    THEN 'Texas Instruments Inc'
  WHEN 'MU'     THEN 'Micron Technology Inc'
  WHEN 'AMAT'   THEN 'Applied Materials Inc'
  WHEN 'LRCX'   THEN 'Lam Research Corporation'
  WHEN 'KLAC'   THEN 'KLA Corporation'
  WHEN 'MRVL'   THEN 'Marvell Technology Inc'
  WHEN 'ORCL'   THEN 'Oracle Corporation'
  WHEN 'CRM'    THEN 'Salesforce Inc'
  WHEN 'NOW'    THEN 'ServiceNow Inc'
  WHEN 'SNOW'   THEN 'Snowflake Inc'
  WHEN 'PLTR'   THEN 'Palantir Technologies Inc'
  WHEN 'PANW'   THEN 'Palo Alto Networks Inc'
  WHEN 'CRWD'   THEN 'CrowdStrike Holdings Inc'
  WHEN 'ZS'     THEN 'Zscaler Inc'
  WHEN 'OKTA'   THEN 'Okta Inc'
  WHEN 'DDOG'   THEN 'Datadog Inc'
  WHEN 'NET'    THEN 'Cloudflare Inc'
  WHEN 'ADBE'   THEN 'Adobe Inc'
  WHEN 'INTU'   THEN 'Intuit Inc'
  WHEN 'ANSS'   THEN 'ANSYS Inc'
  WHEN 'CDNS'   THEN 'Cadence Design Systems Inc'
  WHEN 'SNPS'   THEN 'Synopsys Inc'
  WHEN 'FTNT'   THEN 'Fortinet Inc'
  WHEN 'TEAM'   THEN 'Atlassian Corporation'
  WHEN 'WDAY'   THEN 'Workday Inc'
  WHEN 'VEEV'   THEN 'Veeva Systems Inc'
  WHEN 'PAYC'   THEN 'Paycom Software Inc'
  WHEN 'HUBS'   THEN 'HubSpot Inc'
  WHEN 'ZM'     THEN 'Zoom Video Communications Inc'
  WHEN 'TWLO'   THEN 'Twilio Inc'
  WHEN 'MDB'    THEN 'MongoDB Inc'
  WHEN 'ESTC'   THEN 'Elastic NV'
  WHEN 'U'      THEN 'Unity Software Inc'
  WHEN 'RBLX'   THEN 'Roblox Corporation'
  WHEN 'UBER'   THEN 'Uber Technologies Inc'
  WHEN 'LYFT'   THEN 'Lyft Inc'
  WHEN 'DASH'   THEN 'DoorDash Inc'
  WHEN 'ABNB'   THEN 'Airbnb Inc'
  WHEN 'IONQ'   THEN 'IonQ Inc'
  WHEN 'TSM'    THEN 'Taiwan Semiconductor Manufacturing'
  WHEN 'BABA'   THEN 'Alibaba Group Holding'
  WHEN 'BIDU'   THEN 'Baidu Inc'
  WHEN 'JD'     THEN 'JD.com Inc'
  WHEN 'PDD'    THEN 'PDD Holdings Inc'
  WHEN 'IBM'    THEN 'International Business Machines'
  WHEN 'HPQ'    THEN 'HP Inc'
  WHEN 'HPE'    THEN 'Hewlett Packard Enterprise'
  WHEN 'DELL'   THEN 'Dell Technologies Inc'
  WHEN 'ACN'    THEN 'Accenture PLC'
  WHEN 'IT'     THEN 'Gartner Inc'
  WHEN 'CTSH'   THEN 'Cognizant Technology Solutions'
  WHEN 'EPAM'   THEN 'EPAM Systems Inc'
  WHEN 'QQQ'    THEN 'Invesco QQQ Trust'
  -- Financial Services
  WHEN 'JPM'    THEN 'JPMorgan Chase & Co'
  WHEN 'BAC'    THEN 'Bank of America Corporation'
  WHEN 'WFC'    THEN 'Wells Fargo & Company'
  WHEN 'C'      THEN 'Citigroup Inc'
  WHEN 'GS'     THEN 'Goldman Sachs Group Inc'
  WHEN 'MS'     THEN 'Morgan Stanley'
  WHEN 'BLK'    THEN 'BlackRock Inc'
  WHEN 'SCHW'   THEN 'Charles Schwab Corporation'
  WHEN 'AXP'    THEN 'American Express Company'
  WHEN 'V'      THEN 'Visa Inc'
  WHEN 'MA'     THEN 'Mastercard Inc'
  WHEN 'PYPL'   THEN 'PayPal Holdings Inc'
  WHEN 'SQ'     THEN 'Block Inc'
  WHEN 'COIN'   THEN 'Coinbase Global Inc'
  WHEN 'BX'     THEN 'Blackstone Inc'
  WHEN 'APO'    THEN 'Apollo Global Management Inc'
  WHEN 'KKR'    THEN 'KKR & Co Inc'
  WHEN 'CG'     THEN 'Carlyle Group Inc'
  WHEN 'BAM'    THEN 'Brookfield Asset Management'
  WHEN 'BN'     THEN 'Brookfield Corporation'
  WHEN 'ARES'   THEN 'Ares Management Corporation'
  WHEN 'TPG'    THEN 'TPG Inc'
  WHEN 'BRK.B'  THEN 'Berkshire Hathaway Inc Class B'
  WHEN 'BRK'    THEN 'Berkshire Hathaway Inc Class B'
  WHEN 'BRK.A'  THEN 'Berkshire Hathaway Inc Class A'
  WHEN 'USB'    THEN 'U.S. Bancorp'
  WHEN 'PNC'    THEN 'PNC Financial Services Group'
  WHEN 'TFC'    THEN 'Truist Financial Corporation'
  WHEN 'COF'    THEN 'Capital One Financial Corporation'
  WHEN 'DFS'    THEN 'Discover Financial Services'
  WHEN 'SPGI'   THEN 'S&P Global Inc'
  WHEN 'MCO'    THEN 'Moody''s Corporation'
  WHEN 'ICE'    THEN 'Intercontinental Exchange Inc'
  WHEN 'CME'    THEN 'CME Group Inc'
  WHEN 'CBOE'   THEN 'Cboe Global Markets Inc'
  WHEN 'NDAQ'   THEN 'Nasdaq Inc'
  WHEN 'FIS'    THEN 'Fidelity National Information Services'
  WHEN 'FISV'   THEN 'Fiserv Inc'
  WHEN 'GPN'    THEN 'Global Payments Inc'
  WHEN 'SPMO'   THEN 'Invesco S&P 500 Momentum ETF'
  WHEN 'MUFG'   THEN 'Mitsubishi UFJ Financial Group'
  WHEN 'ING'    THEN 'ING Groep NV'
  WHEN 'DB'     THEN 'Deutsche Bank AG'
  WHEN 'CS'     THEN 'Credit Suisse Group AG'
  WHEN 'UBS'    THEN 'UBS Group AG'
  WHEN 'HSBC'   THEN 'HSBC Holdings PLC'
  WHEN 'BCS'    THEN 'Barclays PLC'
  WHEN 'SPY'    THEN 'SPDR S&P 500 ETF Trust'
  WHEN 'IWM'    THEN 'iShares Russell 2000 ETF'
  WHEN 'TLT'    THEN 'iShares 20+ Year Treasury Bond ETF'
  WHEN 'VXX'    THEN 'iPath Series B S&P 500 VIX Short-Term Futures ETN'
  -- Healthcare & Biotech
  WHEN 'JNJ'    THEN 'Johnson & Johnson'
  WHEN 'UNH'    THEN 'UnitedHealth Group Inc'
  WHEN 'LLY'    THEN 'Eli Lilly and Company'
  WHEN 'MRK'    THEN 'Merck & Co Inc'
  WHEN 'ABBV'   THEN 'AbbVie Inc'
  WHEN 'PFE'    THEN 'Pfizer Inc'
  WHEN 'AMGN'   THEN 'Amgen Inc'
  WHEN 'GILD'   THEN 'Gilead Sciences Inc'
  WHEN 'BIIB'   THEN 'Biogen Inc'
  WHEN 'REGN'   THEN 'Regeneron Pharmaceuticals Inc'
  WHEN 'VRTX'   THEN 'Vertex Pharmaceuticals Inc'
  WHEN 'MRNA'   THEN 'Moderna Inc'
  WHEN 'BNTX'   THEN 'BioNTech SE'
  WHEN 'ILMN'   THEN 'Illumina Inc'
  WHEN 'ISRG'   THEN 'Intuitive Surgical Inc'
  WHEN 'MDT'    THEN 'Medtronic PLC'
  WHEN 'ABT'    THEN 'Abbott Laboratories'
  WHEN 'BSX'    THEN 'Boston Scientific Corporation'
  WHEN 'EW'     THEN 'Edwards Lifesciences Corporation'
  WHEN 'CVS'    THEN 'CVS Health Corporation'
  WHEN 'CI'     THEN 'Cigna Group'
  WHEN 'HUM'    THEN 'Humana Inc'
  WHEN 'MCK'    THEN 'McKesson Corporation'
  WHEN 'CAH'    THEN 'Cardinal Health Inc'
  WHEN 'ZBH'    THEN 'Zimmer Biomet Holdings Inc'
  WHEN 'TMO'    THEN 'Thermo Fisher Scientific Inc'
  WHEN 'DHR'    THEN 'Danaher Corporation'
  WHEN 'IQV'    THEN 'IQVIA Holdings Inc'
  WHEN 'A'      THEN 'Agilent Technologies Inc'
  WHEN 'IDXX'   THEN 'IDEXX Laboratories Inc'
  -- Energy & Oil/Gas
  WHEN 'XOM'    THEN 'Exxon Mobil Corporation'
  WHEN 'CVX'    THEN 'Chevron Corporation'
  WHEN 'COP'    THEN 'ConocoPhillips'
  WHEN 'EOG'    THEN 'EOG Resources Inc'
  WHEN 'PXD'    THEN 'Pioneer Natural Resources'
  WHEN 'SLB'    THEN 'SLB (Schlumberger)'
  WHEN 'HAL'    THEN 'Halliburton Company'
  WHEN 'BKR'    THEN 'Baker Hughes Company'
  WHEN 'OXY'    THEN 'Occidental Petroleum Corporation'
  WHEN 'DVN'    THEN 'Devon Energy Corporation'
  WHEN 'MPC'    THEN 'Marathon Petroleum Corporation'
  WHEN 'PSX'    THEN 'Phillips 66'
  WHEN 'VLO'    THEN 'Valero Energy Corporation'
  WHEN 'KMI'    THEN 'Kinder Morgan Inc'
  WHEN 'WMB'    THEN 'Williams Companies Inc'
  WHEN 'NEE'    THEN 'NextEra Energy Inc'
  WHEN 'DUK'    THEN 'Duke Energy Corporation'
  WHEN 'SO'     THEN 'Southern Company'
  WHEN 'D'      THEN 'Dominion Energy Inc'
  WHEN 'AEP'    THEN 'American Electric Power'
  WHEN 'GLD'    THEN 'SPDR Gold Shares ETF'
  -- Consumer & Retail
  WHEN 'WMT'    THEN 'Walmart Inc'
  WHEN 'COST'   THEN 'Costco Wholesale Corporation'
  WHEN 'TGT'    THEN 'Target Corporation'
  WHEN 'HD'     THEN 'Home Depot Inc'
  WHEN 'LOW'    THEN 'Lowe''s Companies Inc'
  WHEN 'SBUX'   THEN 'Starbucks Corporation'
  WHEN 'MCD'    THEN 'McDonald''s Corporation'
  WHEN 'NKE'    THEN 'Nike Inc'
  WHEN 'LULU'   THEN 'Lululemon Athletica Inc'
  WHEN 'TJX'    THEN 'TJX Companies Inc'
  WHEN 'ROST'   THEN 'Ross Stores Inc'
  WHEN 'KO'     THEN 'Coca-Cola Company'
  WHEN 'PEP'    THEN 'PepsiCo Inc'
  WHEN 'MDLZ'   THEN 'Mondelez International Inc'
  WHEN 'GIS'    THEN 'General Mills Inc'
  WHEN 'K'      THEN 'Kellanova'
  WHEN 'HSY'    THEN 'Hershey Company'
  WHEN 'MO'     THEN 'Altria Group Inc'
  WHEN 'PM'     THEN 'Philip Morris International'
  WHEN 'PG'     THEN 'Procter & Gamble Company'
  WHEN 'CL'     THEN 'Colgate-Palmolive Company'
  WHEN 'EL'     THEN 'Estee Lauder Companies Inc'
  WHEN 'ULTA'   THEN 'Ulta Beauty Inc'
  WHEN 'ETSY'   THEN 'Etsy Inc'
  WHEN 'EBAY'   THEN 'eBay Inc'
  -- Media & Telecom
  WHEN 'NFLX'   THEN 'Netflix Inc'
  WHEN 'DIS'    THEN 'Walt Disney Company'
  WHEN 'PARA'   THEN 'Paramount Global'
  WHEN 'WBD'    THEN 'Warner Bros Discovery Inc'
  WHEN 'CMCSA'  THEN 'Comcast Corporation'
  WHEN 'CHTR'   THEN 'Charter Communications Inc'
  WHEN 'TMUS'   THEN 'T-Mobile US Inc'
  WHEN 'VZ'     THEN 'Verizon Communications Inc'
  WHEN 'T'      THEN 'AT&T Inc'
  WHEN 'SPOT'   THEN 'Spotify Technology SA'
  WHEN 'TTD'    THEN 'Trade Desk Inc'
  WHEN 'SNAP'   THEN 'Snap Inc'
  WHEN 'PINS'   THEN 'Pinterest Inc'
  WHEN 'RDDT'   THEN 'Reddit Inc'
  WHEN 'EA'     THEN 'Electronic Arts Inc'
  WHEN 'TTWO'   THEN 'Take-Two Interactive Software'
  WHEN 'NTES'   THEN 'NetEase Inc'
  -- Industrials & Manufacturing
  WHEN 'BA'     THEN 'Boeing Company'
  WHEN 'GE'     THEN 'GE Aerospace'
  WHEN 'HON'    THEN 'Honeywell International Inc'
  WHEN 'MMM'    THEN '3M Company'
  WHEN 'EMR'    THEN 'Emerson Electric Co'
  WHEN 'ROK'    THEN 'Rockwell Automation Inc'
  WHEN 'PH'     THEN 'Parker-Hannifin Corporation'
  WHEN 'ETN'    THEN 'Eaton Corporation PLC'
  WHEN 'AME'    THEN 'AMETEK Inc'
  WHEN 'IEX'    THEN 'IDEX Corporation'
  WHEN 'XYL'    THEN 'Xylem Inc'
  WHEN 'IR'     THEN 'Ingersoll Rand Inc'
  WHEN 'DOV'    THEN 'Dover Corporation'
  WHEN 'FTV'    THEN 'Fortive Corporation'
  WHEN 'CMI'    THEN 'Cummins Inc'
  WHEN 'PCAR'   THEN 'PACCAR Inc'
  WHEN 'DE'     THEN 'Deere & Company'
  WHEN 'CAT'    THEN 'Caterpillar Inc'
  WHEN 'URI'    THEN 'United Rentals Inc'
  WHEN 'UPS'    THEN 'United Parcel Service Inc'
  WHEN 'FDX'    THEN 'FedEx Corporation'
  WHEN 'LUV'    THEN 'Southwest Airlines Co'
  WHEN 'DAL'    THEN 'Delta Air Lines Inc'
  WHEN 'UAL'    THEN 'United Airlines Holdings Inc'
  WHEN 'AAL'    THEN 'American Airlines Group Inc'
  -- Aerospace & Defense
  WHEN 'LMT'    THEN 'Lockheed Martin Corporation'
  WHEN 'RTX'    THEN 'RTX Corporation (Raytheon)'
  WHEN 'NOC'    THEN 'Northrop Grumman Corporation'
  WHEN 'GD'     THEN 'General Dynamics Corporation'
  WHEN 'HII'    THEN 'Huntington Ingalls Industries'
  WHEN 'L3H'    THEN 'L3Harris Technologies Inc'
  -- Real Estate
  WHEN 'AMT'    THEN 'American Tower Corporation'
  WHEN 'PLD'    THEN 'Prologis Inc'
  WHEN 'EQIX'   THEN 'Equinix Inc'
  WHEN 'CCI'    THEN 'Crown Castle Inc'
  WHEN 'SBAC'   THEN 'SBA Communications Corporation'
  WHEN 'SPG'    THEN 'Simon Property Group Inc'
  WHEN 'VTR'    THEN 'Ventas Inc'
  WHEN 'WELL'   THEN 'Welltower Inc'
  WHEN 'PSA'    THEN 'Public Storage'
  WHEN 'EXR'    THEN 'Extra Space Storage Inc'
  WHEN 'O'      THEN 'Realty Income Corporation'
  WHEN 'VICI'   THEN 'VICI Properties Inc'
  WHEN 'AVB'    THEN 'AvalonBay Communities Inc'
  WHEN 'EQR'    THEN 'Equity Residential'
  -- Materials & Mining
  WHEN 'LIN'    THEN 'Linde PLC'
  WHEN 'APD'    THEN 'Air Products and Chemicals Inc'
  WHEN 'SHW'    THEN 'Sherwin-Williams Company'
  WHEN 'ECL'    THEN 'Ecolab Inc'
  WHEN 'NEM'    THEN 'Newmont Corporation'
  WHEN 'GOLD'   THEN 'Barrick Gold Corporation'
  WHEN 'AA'     THEN 'Alcoa Corporation'
  WHEN 'NUE'    THEN 'Nucor Corporation'
  WHEN 'FCX'    THEN 'Freeport-McMoRan Inc'
  WHEN 'VALE'   THEN 'Vale SA'
  WHEN 'BHP'    THEN 'BHP Group'
  WHEN 'RIO'    THEN 'Rio Tinto PLC'
  -- Agriculture
  WHEN 'MOS'    THEN 'Mosaic Company'
  WHEN 'CF'     THEN 'CF Industries Holdings Inc'
  WHEN 'ADM'    THEN 'Archer-Daniels-Midland Company'
  WHEN 'BG'     THEN 'Bunge Global SA'
  WHEN 'CTVA'   THEN 'Corteva Inc'
  WHEN 'FMC'    THEN 'FMC Corporation'
  ELSE display_name  -- preserve existing value if already set
END
WHERE type = 'ticker'
  AND (display_name IS NULL OR display_name = '');
